// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Diagnostics.Eventing.Reader;
using System.Collections.Generic;
using System.Security.Principal;
using System.Diagnostics.Eventing;
using System.Collections;
using System.Security;

namespace System.Diagnostics.Eventing.Reader {
    public class EventLogRecord: System.Diagnostics.Eventing.Reader.EventRecord {

        public override System.Nullable<System.Guid> ActivityId {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ActivityId));
				return null;
			}
		}
        public override System.Diagnostics.Eventing.Reader.EventBookmark Bookmark {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Bookmark));
				return default (EventBookmark);
			}
		}
        public string ContainerLog {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ContainerLog));
				return default (String);
			}
		}
        public override int Id {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Id));
				return default (Int32);
			}
		}
        public override System.Nullable<long> Keywords {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Keywords));
				return null;
			}
		}
        public override System.Collections.Generic.IEnumerable<string> KeywordsDisplayNames {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(KeywordsDisplayNames));
				return default (IEnumerable<string>);
			}
		}
        public override System.Nullable<byte> Level {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Level));
				return null;
			}
		}
        public override string LevelDisplayName {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(LevelDisplayName));
				return default (String);
			}
		}
        public override string LogName {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(LogName));
				return default (String);
			}
		}
        public override string MachineName {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MachineName));
				return default (String);
			}
		}
        public System.Collections.Generic.IEnumerable<int> MatchedQueryIds {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MatchedQueryIds));
				return default (IEnumerable<int>);
			}
		}
        public override System.Nullable<System.Int16> Opcode {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Opcode));
				return null;
			}
		}
        public override string OpcodeDisplayName {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OpcodeDisplayName));
				return default (String);
			}
		}
        public override System.Nullable<int> ProcessId {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ProcessId));
				return null;
			}
		}
        public override System.Collections.Generic.IList<System.Diagnostics.Eventing.Reader.EventProperty> Properties {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Properties));
				return default (IList<EventProperty>);
			}
		}
        public override System.Nullable<System.Guid> ProviderId {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ProviderId));
				return null;
			}
		}
        public override string ProviderName {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ProviderName));
				return default (String);
			}
		}
        public override System.Nullable<int> Qualifiers {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Qualifiers));
				return null;
			}
		}
        public override System.Nullable<long> RecordId {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RecordId));
				return null;
			}
		}
        public override System.Nullable<System.Guid> RelatedActivityId {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RelatedActivityId));
				return null;
			}
		}
        public override System.Nullable<int> Task {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Task));
				return null;
			}
		}
        public override string TaskDisplayName {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(TaskDisplayName));
				return default (String);
			}
		}
        public override System.Nullable<int> ThreadId {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ThreadId));
				return null;
			}
		}
        public override System.Nullable<System.DateTime> TimeCreated {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(TimeCreated));
				return null;
			}
		}
        public override System.Security.Principal.SecurityIdentifier UserId {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UserId));
				return default (SecurityIdentifier);
			}
		}
        public override System.Nullable<byte> Version {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Version));
				return null;
			}
		}
        protected override void Dispose( bool disposing ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Dispose), typeof(Boolean) );
		}
        public override string FormatDescription() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FormatDescription) );
            return default( string );

		}
        public override string FormatDescription( System.Collections.Generic.IEnumerable<System.Object> values ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FormatDescription), typeof(IEnumerable<object>) );
            return default( string );

		}
        public System.Collections.Generic.IList<System.Object> GetPropertyValues( System.Diagnostics.Eventing.Reader.EventLogPropertySelector propertySelector ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetPropertyValues), typeof(EventLogPropertySelector) );
            return default( System.Collections.Generic.IList<System.Object> );

		}
        public override string ToXml() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToXml) );
            return default( string );

		}
    }
}