// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Diagnostics.Eventing.Reader {
    public class EventProperty {

        public System.Object Value { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Value));
				return default (Object);
			}
		}
    }
}