// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Diagnostics.Eventing.Reader;

namespace System.Diagnostics.Eventing.Reader {
    public enum EventLogIsolation {
        Application = 0,
        Custom = 2,
        System = 1
    }
}