// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Cryptography.X509Certificates;
using System.Security.Cryptography;
using System.Security;

namespace System.Security.Cryptography.X509Certificates {
    public class TimestampInformation {

        public string HashAlgorithm { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HashAlgorithm));
				return default (String);
			}
		}
        public int HResult { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HResult));
				return default (Int32);
			}
		}
        public bool IsValid { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsValid));
				return default (Boolean);
			}
		}
        public System.Security.Cryptography.X509Certificates.X509Chain SignatureChain { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SignatureChain));
				return default (X509Chain);
			}
		}
        public System.Security.Cryptography.X509Certificates.X509Certificate2 SigningCertificate { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SigningCertificate));
				return default (X509Certificate2);
			}
		}
        public System.DateTime Timestamp { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Timestamp));
				return default (DateTime);
			}
		}
        public System.Security.Cryptography.SignatureVerificationResult VerificationResult { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(VerificationResult));
				return default (SignatureVerificationResult);
			}
		}
    }
}