// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Cryptography;

namespace System.Security.Cryptography.X509Certificates {
    public class X509SubjectKeyIdentifierExtension: System.Security.Cryptography.X509Certificates.X509Extension {

        internal const string oid = "2.5.29.14";

        internal const string friendlyName = "Subject Key Identifier";

        public string SubjectKeyIdentifier {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SubjectKeyIdentifier));
				return default (String);
			}
		}
        public X509SubjectKeyIdentifierExtension(  ) : base( default( System.Security.Cryptography.AsnEncodedData ), default( bool ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(X509SubjectKeyIdentifierExtension));
            }
        public X509SubjectKeyIdentifierExtension( System.Security.Cryptography.AsnEncodedData encodedSubjectKeyIdentifier, bool critical ) : base( default( System.Security.Cryptography.AsnEncodedData ), default( bool ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(X509SubjectKeyIdentifierExtension), typeof(AsnEncodedData), typeof(Boolean));
            }
        public X509SubjectKeyIdentifierExtension( byte[] subjectKeyIdentifier, bool critical ) : base( default( System.Security.Cryptography.AsnEncodedData ), default( bool ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(X509SubjectKeyIdentifierExtension), typeof(Byte[]), typeof(Boolean));
            }
        public X509SubjectKeyIdentifierExtension( string subjectKeyIdentifier, bool critical ) : base( default( System.Security.Cryptography.AsnEncodedData ), default( bool ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(X509SubjectKeyIdentifierExtension), typeof(String), typeof(Boolean));
            }
        public X509SubjectKeyIdentifierExtension( System.Security.Cryptography.X509Certificates.PublicKey key, bool critical ) : base( default( System.Security.Cryptography.AsnEncodedData ), default( bool ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(X509SubjectKeyIdentifierExtension), typeof(PublicKey), typeof(Boolean));
            }
        public X509SubjectKeyIdentifierExtension( System.Security.Cryptography.X509Certificates.PublicKey key, System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierHashAlgorithm algorithm, bool critical ) : base( default( System.Security.Cryptography.AsnEncodedData ), default( bool ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(X509SubjectKeyIdentifierExtension), typeof(PublicKey), typeof(X509SubjectKeyIdentifierHashAlgorithm), typeof(Boolean));
            }
        public override void CopyFrom( System.Security.Cryptography.AsnEncodedData asnEncodedData ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CopyFrom), typeof(AsnEncodedData) );
		}
        internal static byte FromHexChar( char c ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FromHexChar), typeof(Char) );
            return default( byte );

		}
        internal static byte FromHexChars( char c1, char c2 ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FromHexChars), typeof(Char), typeof(Char) );
            return default( byte );

		}
        internal static byte[][] FromHex( string hex ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FromHex), typeof(String) );
            return default( byte[][] );

		}
        internal byte[][] Encode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Encode) );
            return default( byte[][] );

		}
        internal override string ToString( bool multiLine ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString), typeof(Boolean) );
            return default( string );

		}
    }
}