// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Security.Principal;
using System;
using System.Security;

namespace System.Security.Principal {
    public class IdentityNotMappedException: System.SystemException {

        public System.Security.Principal.IdentityReferenceCollection UnmappedIdentities {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UnmappedIdentities));
				return default (IdentityReferenceCollection);
			}
		}
        public IdentityNotMappedException(  ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IdentityNotMappedException));
            }
        public IdentityNotMappedException( string message ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IdentityNotMappedException), typeof(String));
            }
        public IdentityNotMappedException( string message, System.Exception inner ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IdentityNotMappedException), typeof(String), typeof(Exception));
            }
        public void GetObjectData( System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetObjectData), typeof(SerializationInfo), typeof(StreamingContext) );
		}
    }
}