// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security.Principal;
using System;
using System.Security;

namespace System.Security.Principal {
    public interface IPrincipal {

        System.Security.Principal.IIdentity Identity { get; }
        bool IsInRole( string role );

    }
}