// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Threading;

namespace System.Threading {
    public enum ApartmentState {
        STA = 0,
        MTA = 1,
        Unknown = 2
    }
}