// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Threading;
using System;

namespace System.Threading {
    public class AsyncLocal<T> {

        public T Value { get; set; }
        public AsyncLocal(  )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AsyncLocal<T>));
            }
        public AsyncLocal( System.Action<System.Threading.AsyncLocalValueChangedArgs<T>> valueChangedHandler )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AsyncLocal<T>), typeof(Action));
            }
    }
}