// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;

namespace System.Threading {
    public class SynchronizationLockException: System.SystemException {

        public SynchronizationLockException(  ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SynchronizationLockException));
            }
        public SynchronizationLockException( string message ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SynchronizationLockException), typeof(String));
            }
        public SynchronizationLockException( string message, System.Exception innerException ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SynchronizationLockException), typeof(String), typeof(Exception));
            }
    }
}