// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;

namespace System.Runtime.ConstrainedExecution {
    public class PrePrepareMethodAttribute: System.Attribute {

    }
}