// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Security.Authentication.ExtendedProtection {
    public abstract class ChannelBinding {

        public abstract int Size { get; }
    }
}