// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System;
using System.Xml;

namespace System.Configuration {
    public class ConfigurationException: System.SystemException {

        public virtual string BareMessage {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(BareMessage));
				return default (String);
			}
		}
        public virtual string Filename {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Filename));
				return default (String);
			}
		}
        public virtual int Line {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Line));
				return default (Int32);
			}
		}
        public override string Message {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Message));
				return default (String);
			}
		}
        public ConfigurationException(  ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ConfigurationException));
            }
        public ConfigurationException( string message ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ConfigurationException), typeof(String));
            }
        public ConfigurationException( string message, System.Exception inner ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ConfigurationException), typeof(String), typeof(Exception));
            }


        public ConfigurationException( string message, string filename, int line ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ConfigurationException), typeof(String), typeof(String), typeof(Int32));
            }
        public ConfigurationException( string message, System.Exception inner, string filename, int line ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ConfigurationException), typeof(String), typeof(Exception), typeof(String), typeof(Int32));
            }

        public void GetObjectData( System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetObjectData), typeof(SerializationInfo), typeof(StreamingContext) );
		}
    }
}