// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Configuration;
using System;

namespace System.Configuration {
    public interface IApplicationSettingsProvider {

        System.Configuration.SettingsPropertyValue GetPreviousVersion( System.Configuration.SettingsContext context, System.Configuration.SettingsProperty property );

        void Reset( System.Configuration.SettingsContext context );

        void Upgrade( System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyCollection properties );

    }
}