// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Configuration {
    public interface IConfigurationSystem {

        System.Object GetConfig( string configKey );

        void Init();

    }
}