// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Configuration;
using System;
using System.Xml;

namespace System.Configuration {
    public class IgnoreSectionHandler: System.Configuration.IConfigurationSectionHandler {

    }
}