// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;

namespace System.Configuration {
    public class SettingsPropertyWrongTypeException: System.Exception {

        public SettingsPropertyWrongTypeException(  ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SettingsPropertyWrongTypeException));
            }
        public SettingsPropertyWrongTypeException( string message ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SettingsPropertyWrongTypeException), typeof(String));
            }
        public SettingsPropertyWrongTypeException( string message, System.Exception innerException ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SettingsPropertyWrongTypeException), typeof(String), typeof(Exception));
            }
    }
}