// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Configuration;

namespace System.Configuration {
    public class SettingsProperty {

        public virtual System.Configuration.SettingsAttributeDictionary Attributes { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Attributes));
				return default (SettingsAttributeDictionary);
			}
		}
        public virtual System.Object DefaultValue { get; set; }
        public virtual bool IsReadOnly { get; set; }
        public virtual string Name { get; set; }
        public virtual System.Type PropertyType { get; set; }
        public virtual System.Configuration.SettingsProvider Provider { get; set; }
        public virtual System.Configuration.SettingsSerializeAs SerializeAs { get; set; }
        public bool ThrowOnErrorDeserializing { get; set; }
        public bool ThrowOnErrorSerializing { get; set; }
        public SettingsProperty( System.Configuration.SettingsProperty propertyToCopy )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SettingsProperty), typeof(SettingsProperty));
            }
        public SettingsProperty( string name )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SettingsProperty), typeof(String));
            }
        public SettingsProperty( string name, System.Type propertyType, System.Configuration.SettingsProvider provider, bool isReadOnly, System.Object defaultValue, System.Configuration.SettingsSerializeAs serializeAs, System.Configuration.SettingsAttributeDictionary attributes, bool throwOnErrorDeserializing, bool throwOnErrorSerializing )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SettingsProperty), typeof(String), typeof(Type), typeof(SettingsProvider), typeof(Boolean), typeof(Object), typeof(SettingsSerializeAs), typeof(SettingsAttributeDictionary), typeof(Boolean), typeof(Boolean));
            }
    }
}