// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Configuration;
using System;

namespace System.Configuration {
    public class SettingsPropertyValue {

        public bool Deserialized { get; set; }
        public bool IsDirty { get; set; }
        public string Name { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Name));
				return default (String);
			}
		}
        public System.Configuration.SettingsProperty Property { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Property));
				return default (SettingsProperty);
			}
		}
        public System.Object PropertyValue { get; set; }
        public System.Object SerializedValue { get; set; }
        public bool UsingDefaultValue { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UsingDefaultValue));
				return default (Boolean);
			}
		}
        public SettingsPropertyValue( System.Configuration.SettingsProperty property )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SettingsPropertyValue), typeof(SettingsProperty));
            }
        internal System.Object Reset() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Reset) );
            return default( System.Object );
        
		}
    }
}