// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security;
using System;
using System.Security.Policy;
using System.Collections.Generic;
using System.Collections;

namespace System.Security.Policy {
    public class ApplicationTrust: System.Security.Policy.EvidenceBase {

        public System.ApplicationIdentity ApplicationIdentity { get; set; }
        public System.Security.Policy.PolicyStatement DefaultGrantSet { get; set; }
        public System.Object ExtraInfo { get; set; }
        public bool IsApplicationTrustedToRun { get; set; }
        public bool Persist { get; set; }
        public System.Collections.Generic.IList<System.Security.Policy.StrongName> FullTrustAssemblies {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FullTrustAssemblies));
				return default (IList<StrongName>);
			}
		}
        public ApplicationTrust(  )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ApplicationTrust));
            }
        public ApplicationTrust( System.ApplicationIdentity applicationIdentity )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ApplicationTrust), typeof(ApplicationIdentity));
            }
        public ApplicationTrust( System.Security.PermissionSet defaultGrantSet, System.Collections.Generic.IEnumerable<System.Security.Policy.StrongName> fullTrustAssemblies )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ApplicationTrust), typeof(PermissionSet), typeof(IEnumerable<StrongName>));
            }
        public void FromXml( System.Security.SecurityElement element ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FromXml), typeof(SecurityElement) );
		}
        public System.Security.SecurityElement ToXml() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToXml) );
            return default( System.Security.SecurityElement );

		}
    }
}