// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security.Policy;
using System;
using System.Security;

namespace System.Security.Policy {
    public class ApplicationSecurityInfo {

        public System.Security.Policy.Evidence ApplicationEvidence { get; set; }
        public System.ApplicationId ApplicationId { get; set; }
        public System.Security.PermissionSet DefaultRequestSet { get; set; }
        public System.ApplicationId DeploymentId { get; set; }
        public ApplicationSecurityInfo( System.ActivationContext activationContext )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ApplicationSecurityInfo), typeof(ActivationContext));
            }
    }
}