// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Collections;
using System.Security.Policy;

namespace System.Security.Policy {
    public class NetCodeGroup: System.Security.Policy.CodeGroup {

        public override string AttributeString {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AttributeString));
				return default (String);
			}
		}
        public override string MergeLogic {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MergeLogic));
				return default (String);
			}
		}
        public override string PermissionSetName {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PermissionSetName));
				return default (String);
			}
		}
        public NetCodeGroup( System.Security.Policy.IMembershipCondition membershipCondition )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(NetCodeGroup), typeof(IMembershipCondition));
            }
        public void AddConnectAccess( string originScheme, System.Security.Policy.CodeConnectAccess connectAccess ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddConnectAccess), typeof(String), typeof(CodeConnectAccess) );
		}
        public override System.Security.Policy.CodeGroup Copy() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy) );
            return default( System.Security.Policy.CodeGroup );

		}
        public override bool Equals( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public System.Collections.DictionaryEntry[][] GetConnectAccessRules() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetConnectAccessRules) );
            return default( System.Collections.DictionaryEntry[][] );

		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
        public override System.Security.Policy.PolicyStatement Resolve( System.Security.Policy.Evidence evidence ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Resolve), typeof(Evidence) );
            return default( System.Security.Policy.PolicyStatement );

		}
        public void ResetConnectAccess() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ResetConnectAccess) );
		}
        public override System.Security.Policy.CodeGroup ResolveMatchingCodeGroups( System.Security.Policy.Evidence evidence ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ResolveMatchingCodeGroups), typeof(Evidence) );
            return default( System.Security.Policy.CodeGroup );

		}
        protected override void CreateXml( System.Security.SecurityElement element, System.Security.Policy.PolicyLevel level ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateXml), typeof(SecurityElement), typeof(PolicyLevel) );
		}
        protected override void ParseXml( System.Security.SecurityElement e, System.Security.Policy.PolicyLevel level ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ParseXml), typeof(SecurityElement), typeof(PolicyLevel) );
		}
    }
}