// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security.Policy;
using System.Security.Cryptography.X509Certificates;
using System;
using System.Security;
using System.Security.Cryptography;

namespace System.Security.Policy {
    public class Publisher: System.Security.Policy.EvidenceBase, System.Security.Policy.IIdentityPermissionFactory {

        public System.Security.Cryptography.X509Certificates.X509Certificate Certificate {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Certificate));
				return default (X509Certificate);
			}
		}
        public Publisher( System.Security.Cryptography.X509Certificates.X509Certificate cert )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Publisher), typeof(X509Certificate));
            }
        public System.Object Copy() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy) );
            return default( System.Object );

		}
        public System.Security.IPermission CreateIdentityPermission( System.Security.Policy.Evidence evidence ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateIdentityPermission), typeof(Evidence) );
            return default( System.Security.IPermission );

		}
        public override bool Equals( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );

		}
    }
}