// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security.Policy;
using System.Security.Permissions;
using System;
using System.Security;

namespace System.Security.Policy {
    public class StrongName: System.Security.Policy.EvidenceBase, System.Security.Policy.IIdentityPermissionFactory {

        public string Name {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Name));
				return default (String);
			}
		}
        public System.Security.Permissions.StrongNamePublicKeyBlob PublicKey {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PublicKey));
				return default (StrongNamePublicKeyBlob);
			}
		}
        public System.Version Version {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Version));
				return default (Version);
			}
		}
        public StrongName( System.Security.Permissions.StrongNamePublicKeyBlob blob, string name, System.Version version )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StrongName), typeof(StrongNamePublicKeyBlob), typeof(String), typeof(Version));
            }
        public System.Object Copy() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy) );
            return default( System.Object );

		}
        public System.Security.IPermission CreateIdentityPermission( System.Security.Policy.Evidence evidence ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateIdentityPermission), typeof(Evidence) );
            return default( System.Security.IPermission );

		}
        public override bool Equals( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );

		}

    }
}