// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;

namespace System {
    public class EntryPointNotFoundException: System.TypeLoadException {

        public EntryPointNotFoundException(  ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(EntryPointNotFoundException));
            }
        public EntryPointNotFoundException( string message ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(EntryPointNotFoundException), typeof(String));
            }
        public EntryPointNotFoundException( string message, System.Exception inner ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(EntryPointNotFoundException), typeof(String), typeof(Exception));
            }
    }
}