// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;

namespace System {
    public class FieldAccessException: System.MemberAccessException {

        public FieldAccessException(  ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FieldAccessException));
            }
        public FieldAccessException( string message ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FieldAccessException), typeof(String));
            }
        public FieldAccessException( string message, System.Exception inner ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FieldAccessException), typeof(String), typeof(Exception));
            }
    }
}