// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;

namespace System {
    public class TypeUnloadedException: System.SystemException {

        public TypeUnloadedException(  ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(TypeUnloadedException));
            }
        public TypeUnloadedException( string message ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(TypeUnloadedException), typeof(String));
            }
        public TypeUnloadedException( string message, System.Exception innerException ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(TypeUnloadedException), typeof(String), typeof(Exception));
            }
    }
}