// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;

namespace System {
    public class UriFormatException: System.FormatException {

        public UriFormatException(  ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UriFormatException));
            }
        public UriFormatException( string textString ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UriFormatException), typeof(String));
            }
        public UriFormatException( string textString, System.Exception e ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UriFormatException), typeof(String), typeof(Exception));
            }
    }
}