// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Text;

namespace System.Text {
    public abstract class DecoderFallback {

        internal static System.Object InternalSyncObject {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InternalSyncObject));
				return default (Object);
			}
		}
        public static System.Text.DecoderFallback ReplacementFallback {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReplacementFallback));
				return default (DecoderFallback);
			}
		}
        public static System.Text.DecoderFallback ExceptionFallback {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ExceptionFallback));
				return default (DecoderFallback);
			}
		}
        public abstract int MaxCharCount { get; }

        internal bool IsMicrosoftBestFitFallback {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsMicrosoftBestFitFallback));
				return default (Boolean);
			}
		}
        public abstract System.Text.DecoderFallbackBuffer CreateFallbackBuffer();

    }
}