// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Text {
    public class DecoderReplacementFallbackBuffer: System.Text.DecoderFallbackBuffer {

        public override int Remaining { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Remaining));
				return default (Int32);
			}
		}
        public DecoderReplacementFallbackBuffer( System.Text.DecoderReplacementFallback fallback )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DecoderReplacementFallbackBuffer), typeof(DecoderReplacementFallback));
            }
        public override bool Fallback( byte[] bytesUnknown, int index ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Fallback), typeof(Byte[]), typeof(Int32) );
            return default( bool );
        
		}
        public override char GetNextChar() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetNextChar) );
            return default( char );
        
		}
        public override bool MovePrevious() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MovePrevious) );
            return default( bool );
        
		}
        public override void Reset() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Reset) ); 
		}
    }
}