// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Text;

namespace System.Text {
    public abstract class EncodingProvider {

        public abstract System.Text.Encoding GetEncoding( string name );

        public abstract System.Text.Encoding GetEncoding( int codepage );

        public virtual System.Text.Encoding GetEncoding( string name, System.Text.EncoderFallback encoderFallback, System.Text.DecoderFallback decoderFallback ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetEncoding), typeof(String), typeof(EncoderFallback), typeof(DecoderFallback) );
            return default( System.Text.Encoding );
        
		}
        public virtual System.Text.Encoding GetEncoding( int codepage, System.Text.EncoderFallback encoderFallback, System.Text.DecoderFallback decoderFallback ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetEncoding), typeof(Int32), typeof(EncoderFallback), typeof(DecoderFallback) );
            return default( System.Text.Encoding );
        
		}
        internal static void AddProvider( System.Text.EncodingProvider provider ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddProvider), typeof(EncodingProvider) ); 
		}
        internal static System.Text.Encoding GetEncodingFromProvider( int codepage ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetEncodingFromProvider), typeof(Int32) );
            return default( System.Text.Encoding );
        
		}
        internal static System.Text.Encoding GetEncodingFromProvider( string encodingName ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetEncodingFromProvider), typeof(String) );
            return default( System.Text.Encoding );
        
		}
        internal static System.Text.Encoding GetEncodingFromProvider( int codepage, System.Text.EncoderFallback enc, System.Text.DecoderFallback dec ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetEncodingFromProvider), typeof(Int32), typeof(EncoderFallback), typeof(DecoderFallback) );
            return default( System.Text.Encoding );
        
		}
        internal static System.Text.Encoding GetEncodingFromProvider( string encodingName, System.Text.EncoderFallback enc, System.Text.DecoderFallback dec ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetEncodingFromProvider), typeof(String), typeof(EncoderFallback), typeof(DecoderFallback) );
            return default( System.Text.Encoding );
        
		}
    }
}