// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Collections.ObjectModel;
using System.Collections;

namespace System.Runtime.InteropServices.WindowsRuntime {
    public class DesignerNamespaceResolveEventArgs: System.EventArgs {

        public string NamespaceName {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(NamespaceName));
				return default (String);
			}
		}
        public System.Collections.ObjectModel.Collection<string> ResolvedAssemblyFiles {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ResolvedAssemblyFiles));
				return default (Collection<string>);
			}
		}
        public DesignerNamespaceResolveEventArgs( string namespaceName )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DesignerNamespaceResolveEventArgs), typeof(String));
            }
    }
}