// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;

namespace System.Runtime.InteropServices.WindowsRuntime {
    public class ReadOnlyArrayAttribute: System.Attribute {

    }
}