// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Runtime.InteropServices.ComTypes {
    public struct DISPPARAMS {

        internal System.IntPtr rgvarg;

        internal System.IntPtr rgdispidNamedArgs;

        internal int cArgs;

        internal int cNamedArgs;

    }
}