// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices.ComTypes;

namespace System.Runtime.InteropServices.ComTypes {
    public interface IEnumFORMATETC {

        void Clone( out System.Runtime.InteropServices.ComTypes.IEnumFORMATETC newEnum );

        int Next( int celt, out System.Runtime.InteropServices.ComTypes.FORMATETC[] rgelt, out int[] pceltFetched );

        int Reset();

        int Skip( int celt );

    }
}