// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices.ComTypes;
using System.Runtime.InteropServices;

namespace System.Runtime.InteropServices.ComTypes {
    public interface ITypeInfo {

        void GetTypeAttr( out System.IntPtr ppTypeAttr );

        void GetTypeComp( out System.Runtime.InteropServices.ComTypes.ITypeComp ppTComp );

        void GetFuncDesc( int index, out System.IntPtr ppFuncDesc );

        void GetVarDesc( int index, out System.IntPtr ppVarDesc );

        void GetNames( int memid, out string[] rgBstrNames, int cMaxNames, out System.Int32 pcNames );

        void GetRefTypeOfImplType( int index, out System.Int32 href );

        void GetImplTypeFlags( int index, out System.Runtime.InteropServices.ComTypes.IMPLTYPEFLAGS pImplTypeFlags );

        void GetIDsOfNames( string[] rgszNames, int cNames, out int[] pMemId );

        void Invoke( System.Object pvInstance, int memid, System.Int16 wFlags, ref System.Runtime.InteropServices.ComTypes.DISPPARAMS pDispParams, System.IntPtr pVarResult, System.IntPtr pExcepInfo, out System.Int32 puArgErr );

        void GetDocumentation( int index, out System.String strName, out System.String strDocString, out System.Int32 dwHelpContext, out System.String strHelpFile );

        void GetDllEntry( int memid, System.Runtime.InteropServices.ComTypes.INVOKEKIND invKind, System.IntPtr pBstrDllName, System.IntPtr pBstrName, System.IntPtr pwOrdinal );

        void GetRefTypeInfo( int hRef, out System.Runtime.InteropServices.ComTypes.ITypeInfo ppTI );

        void AddressOfMember( int memid, System.Runtime.InteropServices.ComTypes.INVOKEKIND invKind, out System.IntPtr ppv );

        void CreateInstance( System.Object pUnkOuter, ref System.Guid riid, out System.Object ppvObj );

        void GetMops( int memid, out System.String pBstrMops );

        void GetContainingTypeLib( out System.Runtime.InteropServices.ComTypes.ITypeLib ppTLB, out System.Int32 pIndex );

        void ReleaseTypeAttr( System.IntPtr pTypeAttr );

        void ReleaseFuncDesc( System.IntPtr pFuncDesc );

        void ReleaseVarDesc( System.IntPtr pVarDesc );

    }
}