// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices.ComTypes;

namespace System.Runtime.InteropServices.ComTypes {
    public struct VARDESC {

        internal int memid;

        internal string lpstrSchema;

        internal System.Runtime.InteropServices.ComTypes.VARDESC.DESCUNION desc;

        internal System.Runtime.InteropServices.ComTypes.ELEMDESC elemdescVar;

        internal System.Int16 wVarFlags;

        internal System.Runtime.InteropServices.ComTypes.VARKIND varkind;

        public struct DESCUNION {

        internal int oInst;

        internal System.IntPtr lpvarValue;

        }
    }
}