// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Diagnostics.Eventing;

namespace System.Diagnostics.Eventing {
    public enum WriteEventErrorCode {
        EventTooBig = 2,
        NoError = 0,
        NoFreeBuffers = 1
    }
}