// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.CodeDom;

namespace System.CodeDom {
    public class CodeNamespace: System.CodeDom.CodeObject {

        public System.CodeDom.CodeTypeDeclarationCollection Types { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Types));
				return default (CodeTypeDeclarationCollection);
			}
		}
        public System.CodeDom.CodeNamespaceImportCollection Imports { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Imports));
				return default (CodeNamespaceImportCollection);
			}
		}
        public string Name { get; set; }
        public System.CodeDom.CodeCommentStatementCollection Comments { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Comments));
				return default (CodeCommentStatementCollection);
			}
		}
        #pragma warning disable 67
        public event System.EventHandler PopulateComments;
        public event System.EventHandler PopulateImports;
        public event System.EventHandler PopulateTypes;
        #pragma warning disable 67

        public CodeNamespace(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeNamespace));
            }
        public CodeNamespace( string name )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeNamespace), typeof(String));
            }
    }
}