// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections;
using System.CodeDom;
using System;

namespace System.CodeDom {
    public class CodeTypeDeclarationCollection: System.Collections.CollectionBase {

        public new System.CodeDom.CodeTypeDeclaration this[int index] {
			get {
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod("indexer");
			return default( System.CodeDom.CodeTypeDeclaration );
		}
			set {
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod("indexer");
		} }
        public CodeTypeDeclarationCollection(  )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeTypeDeclarationCollection));
            }
        public CodeTypeDeclarationCollection( System.CodeDom.CodeTypeDeclarationCollection value )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeTypeDeclarationCollection), typeof(CodeTypeDeclarationCollection));
            }
        public CodeTypeDeclarationCollection( System.CodeDom.CodeTypeDeclaration[] value )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeTypeDeclarationCollection), typeof(CodeTypeDeclaration[]));
            }
        public int Add( System.CodeDom.CodeTypeDeclaration value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Add), typeof(CodeTypeDeclaration) );
            return default( int );

		}
        public void AddRange( System.CodeDom.CodeTypeDeclaration[] value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddRange), typeof(CodeTypeDeclaration[]) );
		}
        public void AddRange( System.CodeDom.CodeTypeDeclarationCollection value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddRange), typeof(CodeTypeDeclarationCollection) );
		}
        public bool Contains( System.CodeDom.CodeTypeDeclaration value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Contains), typeof(CodeTypeDeclaration) );
            return default( bool );

		}
        public void CopyTo( System.CodeDom.CodeTypeDeclaration[] array, int index ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CopyTo), typeof(CodeTypeDeclaration[]), typeof(Int32) );
		}
        public int IndexOf( System.CodeDom.CodeTypeDeclaration value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IndexOf), typeof(CodeTypeDeclaration) );
            return default( int );

		}
        public void Insert( int index, System.CodeDom.CodeTypeDeclaration value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Insert), typeof(Int32), typeof(CodeTypeDeclaration) );
		}
        public void Remove( System.CodeDom.CodeTypeDeclaration value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Remove), typeof(CodeTypeDeclaration) );
		}
    }
}