// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections;
using System.CodeDom;
using System;

namespace System.CodeDom {
    public class CodeTypeParameterCollection: System.Collections.CollectionBase {

        public new System.CodeDom.CodeTypeParameter this[int index] {
			get {
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod("indexer");
			return default( System.CodeDom.CodeTypeParameter );
		}
			set {
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod("indexer");
		} }
        public CodeTypeParameterCollection(  )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeTypeParameterCollection));
            }
        public CodeTypeParameterCollection( System.CodeDom.CodeTypeParameterCollection value )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeTypeParameterCollection), typeof(CodeTypeParameterCollection));
            }
        public CodeTypeParameterCollection( System.CodeDom.CodeTypeParameter[] value )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeTypeParameterCollection), typeof(CodeTypeParameter[]));
            }
        public int Add( System.CodeDom.CodeTypeParameter value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Add), typeof(CodeTypeParameter) );
            return default( int );

		}
        public void Add( string value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Add), typeof(String) );
		}
        public void AddRange( System.CodeDom.CodeTypeParameter[] value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddRange), typeof(CodeTypeParameter[]) );
		}
        public void AddRange( System.CodeDom.CodeTypeParameterCollection value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddRange), typeof(CodeTypeParameterCollection) );
		}
        public bool Contains( System.CodeDom.CodeTypeParameter value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Contains), typeof(CodeTypeParameter) );
            return default( bool );

		}
        public void CopyTo( System.CodeDom.CodeTypeParameter[] array, int index ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CopyTo), typeof(CodeTypeParameter[]), typeof(Int32) );
		}
        public int IndexOf( System.CodeDom.CodeTypeParameter value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IndexOf), typeof(CodeTypeParameter) );
            return default( int );

		}
        public void Insert( int index, System.CodeDom.CodeTypeParameter value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Insert), typeof(Int32), typeof(CodeTypeParameter) );
		}
        public void Remove( System.CodeDom.CodeTypeParameter value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Remove), typeof(CodeTypeParameter) );
		}
    }
}