// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.CodeDom;

namespace System.CodeDom {
    public class CodeTypeParameter: System.CodeDom.CodeObject {

        public string Name { get; set; }
        public System.CodeDom.CodeTypeReferenceCollection Constraints { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Constraints));
				return default (CodeTypeReferenceCollection);
			}
		}
        public System.CodeDom.CodeAttributeDeclarationCollection CustomAttributes { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CustomAttributes));
				return default (CodeAttributeDeclarationCollection);
			}
		}
        public bool HasConstructorConstraint { get; set; }
        public CodeTypeParameter(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeTypeParameter));
            }
        public CodeTypeParameter( string name )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeTypeParameter), typeof(String));
            }
    }
}