// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.CodeDom;
using System;

namespace System.CodeDom {
    public class CodeMethodInvokeExpression: System.CodeDom.CodeExpression {

        public System.CodeDom.CodeMethodReferenceExpression Method { get; set; }
        public System.CodeDom.CodeExpressionCollection Parameters { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Parameters));
				return default (CodeExpressionCollection);
			}
		}
        public CodeMethodInvokeExpression(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeMethodInvokeExpression));
            }
        public CodeMethodInvokeExpression( System.CodeDom.CodeMethodReferenceExpression method, System.CodeDom.CodeExpression[] parameters )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeMethodInvokeExpression), typeof(CodeMethodReferenceExpression), typeof(CodeExpression[]));
            }
        public CodeMethodInvokeExpression( System.CodeDom.CodeExpression targetObject, string methodName, System.CodeDom.CodeExpression[] parameters )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CodeMethodInvokeExpression), typeof(CodeExpression), typeof(String), typeof(CodeExpression[]));
            }
    }
}