// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;

namespace System.Runtime.CompilerServices {
    public class AccessedThroughPropertyAttribute: System.Attribute {

        public string PropertyName { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PropertyName));
				return default (String);
			}
		}
        public AccessedThroughPropertyAttribute( string propertyName )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AccessedThroughPropertyAttribute), typeof(String));
            }
    }
}