// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.CompilerServices;
using System;
using System.Threading.Tasks;
using System.Threading;

namespace System.Runtime.CompilerServices {
    public struct AsyncValueTaskMethodBuilder<TResult> {

        public ValueTask<TResult> Task {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Task));
				return default (ValueTask<TResult>);
			}
		}
        public static System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder<TResult> Create() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Create) );
            return default( System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder<TResult> );

		}
        public void Start<TStateMachine>( ref TStateMachine stateMachine ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Start), typeof(TStateMachine) );
		}
        public void SetStateMachine( System.Runtime.CompilerServices.IAsyncStateMachine stateMachine ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetStateMachine) );
		}
        public void SetResult( TResult result ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetResult), typeof(TResult) );
		}
        public void SetException( System.Exception exception ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetException), typeof(Exception) );
		}
        public void AwaitOnCompleted<TAwaiter, TStateMachine>( ref TAwaiter awaiter, ref TStateMachine stateMachine )
            where TAwaiter : INotifyCompletion {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AwaitOnCompleted), typeof(TAwaiter), typeof(TStateMachine) );
		}
        public void AwaitUnsafeOnCompleted<TAwaiter, TStateMachine>( ref TAwaiter awaiter, ref TStateMachine stateMachine )
            where TAwaiter : ICriticalNotifyCompletion {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AwaitUnsafeOnCompleted), typeof(TAwaiter), typeof(TStateMachine) );
		}
    }
}