// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Runtime.CompilerServices {
    public class Closure {

        public Closure( System.Object[] constants, System.Object[] locals )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Closure), typeof(Object[]), typeof(Object[]));
            }
    }
}