// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System;

namespace System.Runtime.CompilerServices {
    public struct ConfiguredTaskAwaitable<TResult> {

        public System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult> GetAwaiter() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetAwaiter) );
            return default( System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult> );

		}
        public struct ConfiguredTaskAwaiter<T> {

        public bool IsCompleted {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsCompleted));
				return default (Boolean);
			}
		}
        public void OnCompleted( System.Action continuation ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OnCompleted), typeof(Action) );
		}
        public void UnsafeOnCompleted( System.Action continuation ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UnsafeOnCompleted), typeof(Action) );
		}
        public TResult GetResult() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetResult) );
            return default( TResult );

		}
        }
    }
}