// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;

namespace System.Runtime.CompilerServices {
    public abstract class CustomConstantAttribute: System.Attribute {

        public abstract System.Object Value { get; }
    }
}