// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Runtime;

namespace System.Runtime.CompilerServices {
    public class DefaultDependencyAttribute: System.Attribute {

        public System.Runtime.CompilerServices.LoadHint LoadHint { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(LoadHint));
				return default (LoadHint);
			}
		}
        public DefaultDependencyAttribute( System.Runtime.CompilerServices.LoadHint loadHintArgument )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DefaultDependencyAttribute), typeof(LoadHint));
            }
    }
}