// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;

namespace System.Runtime.CompilerServices {
    public class SpecialNameAttribute: System.Attribute {

    }
}