// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;

namespace System.Runtime.CompilerServices {
    public class StateMachineAttribute: System.Attribute {

        public System.Type StateMachineType { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StateMachineType));
				return default (Type);
			}
		}
        public StateMachineAttribute( System.Type stateMachineType )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StateMachineAttribute), typeof(Type));
            }
    }
}