// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.CompilerServices;
using System;

namespace System.Runtime.CompilerServices {
    public class StrongBox<T> : IStrongBox
    {
        public StrongBox(  )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StrongBox<T>));
            }
        public StrongBox( T value )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StrongBox<T>), typeof(T));
            }

        public System.Object Value
        {
            get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(System.Runtime.CompilerServices.IStrongBox.Value));
				return default (Object);
			}
            set => throw new NotImplementedException();
        }
    }
}