// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;

namespace System.Runtime.CompilerServices {
    public class TypeForwardedToAttribute: System.Attribute {

        public System.Type Destination { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Destination));
				return default (Type);
			}
		}
        public TypeForwardedToAttribute( System.Type destination )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(TypeForwardedToAttribute), typeof(Type));
            }
    }
}