// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.Serialization;
using System.Timers;

namespace System.Timers {
    public delegate void ElapsedEventHandler(); 
}