// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.ComponentModel;
using System;
using System.Timers;
using System.Threading;

namespace System.Timers {
    public class Timer: System.ComponentModel.Component, System.ComponentModel.ISupportInitialize {

        public bool AutoReset { get; set; }
        public bool Enabled { get; set; }
        public double Interval { get; set; }
        public override System.ComponentModel.ISite Site { get; set; }
        public System.ComponentModel.ISynchronizeInvoke SynchronizingObject { get; set; }
        #pragma warning disable 67
        public event System.Timers.ElapsedEventHandler Elapsed;
        #pragma warning disable 67

        public Timer(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Timer));
            }
        public Timer( double interval )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Timer), typeof(Double));
            }
        public void BeginInit() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(BeginInit) ); 
		}
        public void Close() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Close) ); 
		}
        protected override void Dispose( bool disposing ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Dispose), typeof(Boolean) ); 
		}
        public void EndInit() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(EndInit) ); 
		}
        public void Start() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Start) ); 
		}
        public void Stop() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Stop) ); 
		}
    }
}