// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.Remoting.Activation;
using System.Runtime.Remoting.Contexts;

namespace System.Runtime.Remoting.Contexts {
    public interface IContextAttribute {

        void GetPropertiesForNewContext( System.Runtime.Remoting.Activation.IConstructionCallMessage msg );

        bool IsContextOK( System.Runtime.Remoting.Contexts.Context ctx, System.Runtime.Remoting.Activation.IConstructionCallMessage msg );

    }
}