// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections;
using System;
using System.Net;
using System.Collections.Specialized;

namespace System.Net {
    public class AuthenticationManager {

        public static System.Net.ICredentialPolicy CredentialPolicy { get; set; }
        public static System.Collections.Specialized.StringDictionary CustomTargetNameDictionary { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CustomTargetNameDictionary));
				return default (StringDictionary);
			}
		}
        public static System.Collections.IEnumerator RegisteredModules { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RegisteredModules));
				return default (IEnumerator);
			}
		}
        internal static bool OSSupportsExtendedProtection { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OSSupportsExtendedProtection));
				return default (Boolean);
			}
		}
        internal static void Clear() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Clear) ); 
		}
        public static System.Net.Authorization Authenticate( string challenge, System.Net.WebRequest request, System.Net.ICredentials credentials ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Authenticate), typeof(String), typeof(WebRequest), typeof(ICredentials) );
            return default( System.Net.Authorization );
        
		}
        public static System.Net.Authorization PreAuthenticate( System.Net.WebRequest request, System.Net.ICredentials credentials ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PreAuthenticate), typeof(WebRequest), typeof(ICredentials) );
            return default( System.Net.Authorization );
        
		}
        public static void Register( System.Net.IAuthenticationModule authenticationModule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Register), typeof(IAuthenticationModule) ); 
		}
        public static void Unregister( System.Net.IAuthenticationModule authenticationModule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Unregister), typeof(IAuthenticationModule) ); 
		}
        public static void Unregister( string authenticationScheme ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Unregister), typeof(String) ); 
		}
    }
}