// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Net;
using System.Collections;
using System;

namespace System.Net {
    public class CredentialCache: System.Net.ICredentials, System.Collections.IEnumerable, System.Net.ICredentialsByHost {

        internal bool IsDefaultInCache {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsDefaultInCache));
				return default (Boolean);
			}
		}
        public static System.Net.ICredentials DefaultCredentials {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DefaultCredentials));
				return default (ICredentials);
			}
		}
        public static System.Net.NetworkCredential DefaultNetworkCredentials {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DefaultNetworkCredentials));
				return default (NetworkCredential);
			}
		}
        public void Add( System.Uri uriPrefix, string authType, System.Net.NetworkCredential cred ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Add), typeof(Uri), typeof(String), typeof(NetworkCredential) );
		}
        public void Add( string host, int port, string authenticationType, System.Net.NetworkCredential credential ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Add), typeof(String), typeof(Int32), typeof(String), typeof(NetworkCredential) );
		}
        public void Remove( System.Uri uriPrefix, string authType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Remove), typeof(Uri), typeof(String) );
		}
        public void Remove( string host, int port, string authenticationType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Remove), typeof(String), typeof(Int32), typeof(String) );
		}
        public System.Net.NetworkCredential GetCredential( System.Uri uriPrefix, string authType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetCredential), typeof(Uri), typeof(String) );
            return default( System.Net.NetworkCredential );

		}
        public System.Net.NetworkCredential GetCredential( string host, int port, string authenticationType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetCredential), typeof(String), typeof(Int32), typeof(String) );
            return default( System.Net.NetworkCredential );

		}
        public System.Collections.IEnumerator GetEnumerator() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetEnumerator) );
            return default( System.Collections.IEnumerator );

		}
    }
}