// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Net.Sockets;
using System.Net;

namespace System.Net {
    public class DnsEndPoint: System.Net.EndPoint {

        public string Host { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Host));
				return default (String);
			}
		}
        public override System.Net.Sockets.AddressFamily AddressFamily { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddressFamily));
				return default (AddressFamily);
			}
		}
        public int Port { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Port));
				return default (Int32);
			}
		}
        public DnsEndPoint( string host, int port )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DnsEndPoint), typeof(String), typeof(Int32));
            }
        public DnsEndPoint( string host, int port, System.Net.Sockets.AddressFamily addressFamily )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DnsEndPoint), typeof(String), typeof(Int32), typeof(AddressFamily));
            }
        public override bool Equals( System.Object comparand ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );
        
		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );
        
		}
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );
        
		}
    }
}