// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Net {
    public static class Ftp {

        internal const string DownloadFile = "RETR";

        internal const string ListDirectory = "NLST";

        internal const string UploadFile = "STOR";

        internal const string DeleteFile = "DELE";

        internal const string AppendFile = "APPE";

        internal const string GetFileSize = "SIZE";

        internal const string UploadFileWithUniqueName = "STOU";

        internal const string MakeDirectory = "MKD";

        internal const string RemoveDirectory = "RMD";

        internal const string ListDirectoryDetails = "LIST";

        internal const string GetDateTimestamp = "MDTM";

        internal const string PrintWorkingDirectory = "PWD";

        internal const string Rename = "RENAME";

    }
}