// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Net;
using System.Security.Cryptography.X509Certificates;

namespace System.Net {
    public interface ICertificatePolicy {

        bool CheckValidationResult( System.Net.ServicePoint srvPoint, System.Security.Cryptography.X509Certificates.X509Certificate certificate, System.Net.WebRequest request, int certificateProblem );

    }
}