// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Net;
using System;

namespace System.Net {
    public interface ICredentials {

        System.Net.NetworkCredential GetCredential( System.Uri uri, string authType );

    }
}