// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Net;
using System;

namespace System.Net {
    public interface IWebRequestCreate {

        System.Net.WebRequest Create( System.Uri uri );

    }
}