// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Net {
    public static class WebRequestMethods {

        public static class Ftp {

        internal const string DownloadFile = "RETR";

        internal const string ListDirectory = "NLST";

        internal const string UploadFile = "STOR";

        internal const string DeleteFile = "DELE";

        internal const string AppendFile = "APPE";

        internal const string GetFileSize = "SIZE";

        internal const string UploadFileWithUniqueName = "STOU";

        internal const string MakeDirectory = "MKD";

        internal const string RemoveDirectory = "RMD";

        internal const string ListDirectoryDetails = "LIST";

        internal const string GetDateTimestamp = "MDTM";

        internal const string PrintWorkingDirectory = "PWD";

        internal const string Rename = "RENAME";

        }
        public static class Http {

        internal const string Get = "GET";

        internal const string Connect = "CONNECT";

        internal const string Head = "HEAD";

        internal const string Put = "PUT";

        internal const string Post = "POST";

        internal const string MkCol = "MKCOL";

        }
        public static class File {

        internal const string DownloadFile = "GET";

        internal const string UploadFile = "PUT";

        }
    }
}