// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Net.Configuration;
using System.IO;
using System.Net;
using System.Text;

namespace System.Net {
    public static class WebUtility {

        internal static System.Net.Configuration.UnicodeDecodingConformance HtmlDecodeConformance { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HtmlDecodeConformance));
				return default (UnicodeDecodingConformance);
			}
		}
        internal static System.Net.Configuration.UnicodeEncodingConformance HtmlEncodeConformance { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HtmlEncodeConformance));
				return default (UnicodeEncodingConformance);
			}
		}
        public static string HtmlEncode( string value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HtmlEncode), typeof(String) );
            return default( string );
        
		}
        public static void HtmlEncode( string value, System.IO.TextWriter output ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HtmlEncode), typeof(String), typeof(TextWriter) ); 
		}
        public static string HtmlDecode( string value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HtmlDecode), typeof(String) );
            return default( string );
        
		}
        public static void HtmlDecode( string value, System.IO.TextWriter output ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HtmlDecode), typeof(String), typeof(TextWriter) ); 
		}
        public static string UrlEncode( string value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UrlEncode), typeof(String) );
            return default( string );
        
		}
        public static byte[][] UrlEncodeToBytes( byte[] value, int offset, int count ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UrlEncodeToBytes), typeof(Byte[]), typeof(Int32), typeof(Int32) );
            return default( byte[][] );
        
		}
        public static string UrlDecode( string encodedValue ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UrlDecode), typeof(String) );
            return default( string );
        
		}
        public static byte[][] UrlDecodeToBytes( byte[] encodedValue, int offset, int count ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UrlDecodeToBytes), typeof(Byte[]), typeof(Int32), typeof(Int32) );
            return default( byte[][] );
        
		}
    }
}