// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Net {
    public class WriteStreamClosedEventArgs: System.EventArgs {

        public System.Exception Error { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Error));
				return default (Exception);
			}
		}
    }
}