// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.ComponentModel.Design {
    public class CommandID {

        public virtual int ID { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ID));
				return default (Int32);
			}
		}
        public virtual System.Guid Guid { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Guid));
				return default (Guid);
			}
		}
        public CommandID( System.Guid menuGroup, int commandID )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CommandID), typeof(Guid), typeof(Int32));
            }
        public override bool Equals( System.Object obj ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );
        
		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );
        
		}
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );
        
		}
    }
}