// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.ComponentModel.Design;
using System;

namespace System.ComponentModel.Design {
    public class HelpKeywordAttribute: System.Attribute {

        public string HelpKeyword {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HelpKeyword));
				return default (String);
			}
		}
        public HelpKeywordAttribute(  )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HelpKeywordAttribute));
            }
        public HelpKeywordAttribute( string keyword )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HelpKeywordAttribute), typeof(String));
            }
        public HelpKeywordAttribute( System.Type t )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HelpKeywordAttribute), typeof(Type));
            }
        public override bool Equals( System.Object obj ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
    }
}