// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel.Design;

namespace System.ComponentModel.Design {
    public enum HelpContextType {
        Ambient = 0,
        Window = 1,
        Selection = 2,
        ToolWindowSelection = 3
    }
}