// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel.Design;

namespace System.ComponentModel.Design {
    public enum HelpKeywordType {
        F1Keyword = 0,
        GeneralKeyword = 1,
        FilterKeyword = 2
    }
}