// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.ComponentModel;

namespace System.ComponentModel.Design {
    public interface IExtenderListService {

        System.ComponentModel.IExtenderProvider[][] GetExtenderProviders();

    }
}