// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel;

namespace System.ComponentModel.Design {
    public interface IExtenderProviderService {

        void AddExtenderProvider( System.ComponentModel.IExtenderProvider provider );

        void RemoveExtenderProvider( System.ComponentModel.IExtenderProvider provider );

    }
}