// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.ComponentModel.Design;
using System;
using System.ComponentModel;

namespace System.ComponentModel.Design {
    public interface IRootDesigner: System.ComponentModel.Design.IDesigner {

        System.ComponentModel.Design.ViewTechnology[][] SupportedTechnologies { get; }
        System.Object GetView( System.ComponentModel.Design.ViewTechnology technology );

    }
}