// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel.Design;

namespace System.ComponentModel.Design {
    public enum SelectionTypes {
        Auto = 1,
        Normal = 1,
        Replace = 2,
        MouseDown = 4,
        MouseUp = 8,
        Click = 16,
        Primary = 16,
        Toggle = 32,
        Add = 64,
        Remove = 128,
        Valid = 31
    }
}