// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.ComponentModel;
using System;

namespace System.ComponentModel.Design {
    public abstract class TypeDescriptionProviderService {

        public abstract System.ComponentModel.TypeDescriptionProvider GetProvider( System.Object instance );

        public abstract System.ComponentModel.TypeDescriptionProvider GetProvider( System.Type type );

    }
}