// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Remoting.Metadata;
using System;
using System.Runtime.Remoting;

namespace System.Runtime.Remoting.Metadata {
    public class SoapTypeAttribute: System.Runtime.Remoting.Metadata.SoapAttribute {

        public System.Runtime.Remoting.Metadata.SoapOption SoapOptions { get; set; }
        public override bool UseAttribute { get; set; }
        public string XmlElementName { get; set; }
        public System.Runtime.Remoting.Metadata.XmlFieldOrderOption XmlFieldOrder { get; set; }
        public override string XmlNamespace { get; set; }
        public string XmlTypeName { get; set; }
        public string XmlTypeNamespace { get; set; }
        internal bool IsInteropXmlElement { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsInteropXmlElement));
				return default (Boolean);
			}
		}
        internal bool IsInteropXmlType { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsInteropXmlType));
				return default (Boolean);
			}
		}
        internal override void SetReflectionObject( System.Object reflectionObject ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetReflectionObject), typeof(Object) ); 
		}
    }
}