// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Linq.Expressions;
using System;
using System.Dynamic;
using System.Linq;

namespace System.Dynamic {
    public abstract class BinaryOperationBinder: System.Dynamic.DynamicMetaObjectBinder {

        public override System.Type ReturnType { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReturnType));
				return default (Type);
			}
		}
        public System.Linq.Expressions.ExpressionType Operation { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Operation));
				return default (ExpressionType);
			}
		}
        internal override bool IsStandardBinder { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsStandardBinder));
				return default (Boolean);
			}
		}
        public System.Dynamic.DynamicMetaObject FallbackBinaryOperation( System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject arg ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FallbackBinaryOperation), typeof(DynamicMetaObject), typeof(DynamicMetaObject) );
            return default( System.Dynamic.DynamicMetaObject );
        
		}
        public abstract System.Dynamic.DynamicMetaObject FallbackBinaryOperation( System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject arg, System.Dynamic.DynamicMetaObject errorSuggestion );

        public override System.Dynamic.DynamicMetaObject Bind( System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject[] args ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Bind), typeof(DynamicMetaObject), typeof(DynamicMetaObject[]) );
            return default( System.Dynamic.DynamicMetaObject );
        
		}
        internal static bool OperationIsValid( System.Linq.Expressions.ExpressionType operation ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OperationIsValid), typeof(ExpressionType) );
            return default( bool );
        
		}
    }
}