// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections;
using System;

namespace System.ComponentModel.Design.Serialization {
    public class ContextStack {

        public System.Object Current {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Current));
				return default (Object);
			}
		}
        public System.Object this[int level] {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod("indexer");
				return default (Object);
			}
		}
        public System.Object this[System.Type type] {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod("indexer");
				return default (Object);
			}
		}
        public void Append( System.Object context ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Append), typeof(Object) );
		}
        public System.Object Pop() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Pop) );
            return default( System.Object );

		}
        public void Push( System.Object context ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Push), typeof(Object) );
		}
    }
}