// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel;

namespace System.ComponentModel.Design.Serialization {
    public interface INameCreationService {

        string CreateName( System.ComponentModel.IContainer container, System.Type dataType );

        bool IsValidName( string name );

        void ValidateName( string name );

    }
}