// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.ComponentModel.Design.Serialization {
    public class ResolveNameEventArgs: System.EventArgs {

        public string Name { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Name));
				return default (String);
			}
		}
        public System.Object Value { get; set; }
        public ResolveNameEventArgs( string name )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ResolveNameEventArgs), typeof(String));
            }
    }
}