// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.IO.Ports;
using System.IO;

namespace System.IO.Ports {
    public class SerialPinChangedEventArgs: System.EventArgs {

        public System.IO.Ports.SerialPinChange EventType { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(EventType));
				return default (SerialPinChange);
			}
		}
    }
}