// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.IO.Ports;

namespace System.IO.Ports {
    public enum StopBits {
        None = 0,
        One = 1,
        Two = 2,
        OnePointFive = 3
    }
}