// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Cryptography;

namespace System.Security.Cryptography {
    public enum CngKeyHandleOpenOptions {
        None = 0,
        EphemeralKey = 1
    }
}