// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Cryptography;

namespace System.Security.Cryptography {
    public enum CngKeyCreationOptions {
        None = 0,
        MachineKey = 32,
        OverwriteExistingKey = 128
    }
}