// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Cryptography;

namespace System.Security.Cryptography {
    public enum CngUIProtectionLevels {
        None = 0,
        ProtectKey = 1,
        ForceHighProtection = 2
    }
}