// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Cryptography;
using System.Security.AccessControl;
using System.Security;

namespace System.Security.Cryptography {

    public class CspParameters {
        public int ProviderType;
        public string ProviderName;
        public string KeyContainerName;
        public int KeyNumber;
        public CspParameters( int dwTypeIn ) { }
        public CspParameters( int dwTypeIn, string strProviderNameIn ) { }
        public CspParameters( int dwTypeIn, string strProviderNameIn, string strContainerNameIn ) { }

        public CspParameters( int providerType, string providerName, string keyContainerName,
            CryptoKeySecurity cryptoKeySecurity, SecureString keyPassword ) { }

        public CspParameters( int providerType, string providerName, string keyContainerName,
            //Instead of int there are should be IntPtr,
            //but we can't use it because Bridge don't support it
            CryptoKeySecurity cryptoKeySecurity, int parentWindowHandle ) { }

        public CspParameters() { }

        public CspProviderFlags Flags {
            get => default( CspProviderFlags );
            set { }
        }

        public CryptoKeySecurity CryptoKeySecurity {
            get => default( CryptoKeySecurity );
            set { }
        }

        public SecureString KeyPassword {
            get => default( SecureString );
            set { }
        }

        //Instead of int there are should be IntPtr,
        //but we can't use it because Bridge don't support it
        public int ParentWindowHandle {
            get => default( int );
            set { }
        }
    }

}
