// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Cryptography;
using System.Security;

namespace System.Security.Cryptography {
    public class DSACng: System.Security.Cryptography.DSA {

        public System.Security.Cryptography.CngKey Key { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Key));
				return default (CngKey);
			}
		}
        public DSACng(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DSACng));
            }
        public DSACng( int keySize )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DSACng), typeof(Int32));
            }
        public DSACng( System.Security.Cryptography.CngKey key )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DSACng), typeof(CngKey));
            }
        public override byte[][] CreateSignature( byte[] rgbHash ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateSignature), typeof(Byte[]) );
            return default( byte[][] );
        
		}
        public override System.Security.Cryptography.DSAParameters ExportParameters( bool includePrivateParameters ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ExportParameters), typeof(Boolean) );
            return default( System.Security.Cryptography.DSAParameters );
        
		}
        public override void ImportParameters( System.Security.Cryptography.DSAParameters parameters ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ImportParameters), typeof(DSAParameters) ); 
		}
        public override bool VerifySignature( byte[] rgbHash, byte[] rgbSignature ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(VerifySignature), typeof(Byte[]), typeof(Byte[]) );
            return default( bool );
        
		}
    }
}