// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security.Cryptography;
using System;

namespace System.Security.Cryptography {
    public class DSASignatureFormatter: System.Security.Cryptography.AsymmetricSignatureFormatter {

        public DSASignatureFormatter(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DSASignatureFormatter));
            }
        public DSASignatureFormatter( System.Security.Cryptography.AsymmetricAlgorithm key )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DSASignatureFormatter), typeof(AsymmetricAlgorithm));
            }
        public override void SetKey( System.Security.Cryptography.AsymmetricAlgorithm key ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetKey), typeof(AsymmetricAlgorithm) ); 
		}
        public override void SetHashAlgorithm( string strName ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetHashAlgorithm), typeof(String) ); 
		}
        public override byte[][] CreateSignature( byte[] rgbHash ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateSignature), typeof(Byte[]) );
            return default( byte[][] );
        
		}
    }
}