// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Cryptography;

namespace System.Security.Cryptography {
    public enum ECDiffieHellmanKeyDerivationFunction {
        Hash = 0,
        Hmac = 1,
        Tls = 2
    }
}