// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Security.Cryptography {
    public struct ECPoint {

        internal byte[] X;

        internal byte[] Y;

    }
}