// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security.Cryptography;
using System;

namespace System.Security.Cryptography {
    public class HMACSHA384: System.Security.Cryptography.HMAC {

        internal int BlockSize { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(BlockSize));
				return default (Int32);
			}
		}
        public bool ProduceLegacyHmacValues { get; set; }
        public HMACSHA384(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HMACSHA384));
            }
        public HMACSHA384( byte[] key )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HMACSHA384), typeof(Byte[]));
            }
    }
}