// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security.Cryptography;
using System;

namespace System.Security.Cryptography {
    public class HMACRIPEMD160: System.Security.Cryptography.HMAC {

        public HMACRIPEMD160(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HMACRIPEMD160));
            }
        public HMACRIPEMD160( byte[] key )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HMACRIPEMD160), typeof(Byte[]));
            }
    }
}