// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Cryptography;
using System.Security;

namespace System.Security.Cryptography {
    public interface ICspAsymmetricAlgorithm {

        System.Security.Cryptography.CspKeyContainerInfo CspKeyContainerInfo { get; }
        byte[][] ExportCspBlob( bool includePrivateParameters );

        void ImportCspBlob( byte[] rawData );

    }
}