// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Cryptography;

namespace System.Security.Cryptography {
    public enum KeyNumber {
        Exchange = 1,
        Signature = 2
    }
}