// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security.Cryptography;
using System;
using System.Security;

namespace System.Security.Cryptography {
    public class MACTripleDES: System.Security.Cryptography.KeyedHashAlgorithm {

        public System.Security.Cryptography.PaddingMode Padding { get; set; }
        public MACTripleDES(  )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MACTripleDES));
            }
        public MACTripleDES( byte[] rgbKey )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MACTripleDES), typeof(Byte[]));
            }
        public MACTripleDES( string strTripleDES, byte[] rgbKey )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MACTripleDES), typeof(String), typeof(Byte[]));
            }
        public void Initialize() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Initialize) );
		}
        protected void HashCore( byte[] rgbData, int ibStart, int cbSize ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HashCore), typeof(Byte[]), typeof(Int32), typeof(Int32) );
		}
        protected byte[][] HashFinal() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(HashFinal) );
            return default( byte[][] );

		}
        protected new void Dispose( bool disposing ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Dispose), typeof(Boolean) );
		}
    }
}