// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections;
using System.Security.Cryptography;
using System;
using System.Security;

namespace System.Security.Cryptography {
    public class OidEnumerator: System.Collections.IEnumerator {

        public System.Security.Cryptography.Oid Current {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Current));
				return default (Oid);
			}
		}
        System.Object @System.Collections.IEnumerator.Current {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(System.Collections.IEnumerator.Current));
				return default (Object);
			}
		}
        public bool MoveNext() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MoveNext) );
            return default( bool );

		}
        public void Reset() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Reset) );
		}
    }
}