// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Security.Cryptography {
    public class PKCS1MaskGenerationMethod: System.Security.Cryptography.MaskGenerationMethod {

        public string HashName { get; set; }
        public override byte[][] GenerateMask( byte[] rgbSeed, int cbReturn ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GenerateMask), typeof(Byte[]), typeof(Int32) );
            return default( byte[][] );
        
		}
    }
}