// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security.Cryptography;
using System;

namespace System.Security.Cryptography {
    public abstract class SHA256: System.Security.Cryptography.HashAlgorithm {

        public static System.Security.Cryptography.SHA256 Create() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Create) );
            return default( System.Security.Cryptography.SHA256 );
        
		}
        public static System.Security.Cryptography.SHA256 Create( string hashName ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Create), typeof(String) );
            return default( System.Security.Cryptography.SHA256 );
        
		}
    }
}