// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Cryptography;

namespace System.Security.Cryptography {
    public abstract class TripleDES: System.Security.Cryptography.SymmetricAlgorithm {

        public override byte[] Key { get; set; }
        public new static System.Security.Cryptography.TripleDES Create() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Create) );
            return default( System.Security.Cryptography.TripleDES );

		}
        public new static System.Security.Cryptography.TripleDES Create( string str ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Create), typeof(String) );
            return default( System.Security.Cryptography.TripleDES );

		}
        public static bool IsWeakKey( byte[] rgbKey ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsWeakKey), typeof(Byte[]) );
            return default( bool );

		}
    }
}