// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Authentication;

namespace System.Security.Authentication {
    public enum ExchangeAlgorithmType {
        None = 0,
        DiffieHellman = 43522,
        RsaKeyX = 41984,
        RsaSign = 9216
    }
}