// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Diagnostics;

namespace System.Diagnostics {
    public class DefaultTraceListener: System.Diagnostics.TraceListener {

        public bool AssertUiEnabled { get; set; }
        public string LogFileName { get; set; }
        public override void Fail( string message ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Fail), typeof(String) );
		}
        public override void Fail( string message, string detailMessage ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Fail), typeof(String), typeof(String) );
		}
        public override void Write( string message ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Write), typeof(String) );
		}
        public override void WriteLine( string message ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteLine), typeof(String) );
		}
    }
}