// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections;
using System.Diagnostics;
using System;

namespace System.Diagnostics {
    public class InstanceDataCollectionCollection: System.Collections.DictionaryBase {

        public new System.Diagnostics.InstanceDataCollection this[string counterName] {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod("indexer");
				return default (InstanceDataCollection);
			}
		}
        public new System.Collections.ICollection Keys {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Keys));
				return default (ICollection);
			}
		}
        public new System.Collections.ICollection Values {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Values));
				return default (ICollection);
			}
		}
        public bool Contains( string counterName ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Contains), typeof(String) );
            return default( bool );

		}
        public void CopyTo( System.Diagnostics.InstanceDataCollection[] counters, int index ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CopyTo), typeof(InstanceDataCollection[]), typeof(Int32) );
		}
    }
}