// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Diagnostics;

namespace System.Diagnostics {
    public enum PerformanceCounterInstanceLifetime {
        Global = 0,
        Process = 1
    }
}