// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Diagnostics;

namespace System.Diagnostics {
    public class PerformanceCounterManager: System.Diagnostics.ICollectData {

        void @System.Diagnostics.ICollectData.CloseData() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(@System.Diagnostics.ICollectData.CloseData) );
		}
        void @System.Diagnostics.ICollectData.CollectData( int callIdx, System.IntPtr valueNamePtr, System.IntPtr dataPtr, int totalBytes, out System.IntPtr res ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(@System.Diagnostics.ICollectData.CollectData), typeof(Int32), typeof(IntPtr), typeof(IntPtr), typeof(Int32), typeof(IntPtr) );
            res = default( System.IntPtr );

		}
    }
}