// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Linq.Expressions {
    public class SymbolDocumentInfo {
        public string FileName {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FileName));
				return default (String);
			}
		}
        public virtual System.Guid Language {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Language));
				return default (Guid);
			}
		}
        public virtual System.Guid LanguageVendor {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(LanguageVendor));
				return default (Guid);
			}
		}
        public virtual System.Guid DocumentType {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DocumentType));
				return default (Guid);
			}
		}
    }
}