// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Net.Security;

namespace System.Net.Security {
    public enum ProtectionLevel {
        None = 0,
        Sign = 1,
        EncryptAndSign = 2
    }
}