// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.IO;
using System.Net.Mime;
using System.Text;
using System.Net.Mail;
using System.Net;

namespace System.Net.Mail {
    public class Attachment: System.Net.Mail.AttachmentBase {

        public System.Net.Mime.ContentDisposition ContentDisposition {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ContentDisposition));
				return default (ContentDisposition);
			}
		}
        public string Name { get; set; }
        public System.Text.Encoding NameEncoding { get; set; }
        public Attachment( string fileName )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Attachment), typeof(String));
            }
        public Attachment( string fileName, string mediaType )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Attachment), typeof(String), typeof(String));
            }
        public Attachment( string fileName, System.Net.Mime.ContentType contentType )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Attachment), typeof(String), typeof(ContentType));
            }
        public Attachment( System.IO.Stream contentStream, System.Net.Mime.ContentType contentType )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Attachment), typeof(Stream), typeof(ContentType));
            }
        public Attachment( System.IO.Stream contentStream, string name )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Attachment), typeof(Stream), typeof(String));
            }
        public Attachment( System.IO.Stream contentStream, string name, string mediaType )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Attachment), typeof(Stream), typeof(String), typeof(String));
            }
        public static System.Net.Mail.Attachment CreateAttachmentFromString( string content, System.Net.Mime.ContentType contentType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateAttachmentFromString), typeof(String), typeof(ContentType) );
            return default( System.Net.Mail.Attachment );

		}
        public static System.Net.Mail.Attachment CreateAttachmentFromString( string content, string name ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateAttachmentFromString), typeof(String), typeof(String) );
            return default( System.Net.Mail.Attachment );

		}
        public static System.Net.Mail.Attachment CreateAttachmentFromString( string content, string name, System.Text.Encoding contentEncoding, string mediaType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateAttachmentFromString), typeof(String), typeof(String), typeof(Encoding), typeof(String) );
            return default( System.Net.Mail.Attachment );

		}
    }
}