// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Net;
using System;

namespace System.Net.NetworkInformation {
    public abstract class GatewayIPAddressInformation {

        public abstract System.Net.IPAddress Address { get; }
    }
}