// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Net.NetworkInformation;

namespace System.Net.NetworkInformation {
    public abstract class IPv6InterfaceProperties {

        public abstract int Index { get; }

        public abstract int Mtu { get; }

        public virtual long GetScopeId( System.Net.NetworkInformation.ScopeLevel scopeLevel ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetScopeId), typeof(ScopeLevel) );
            return default( long );

		}
    }
}