// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Net;
using System.Net.NetworkInformation;
using System;

namespace System.Net.NetworkInformation {
    public abstract class TcpConnectionInformation {

        public abstract System.Net.IPEndPoint LocalEndPoint { get; }

        public abstract System.Net.IPEndPoint RemoteEndPoint { get; }

        public abstract System.Net.NetworkInformation.TcpState State { get; }
    }
}