// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices;

namespace System.Runtime.InteropServices {
    public enum ClassInterfaceType {
        None = 0,
        AutoDispatch = 1,
        AutoDual = 2
    }
}