// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Reflection;
using System;

namespace System.Runtime.InteropServices {
    public class ComAwareEventInfo {

        public System.Reflection.EventAttributes Attributes {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Attributes));
				return default (EventAttributes);
			}
		}
        public System.Type DeclaringType {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DeclaringType));
				return default (Type);
			}
		}
        public string Name {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Name));
				return default (String);
			}
		}
        public System.Type ReflectedType {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReflectedType));
				return default (Type);
			}
		}
        public ComAwareEventInfo( System.Type type, string eventName )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ComAwareEventInfo), typeof(Type), typeof(String));
            }
        public void AddEventHandler( System.Object target, System.Delegate handler ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddEventHandler), typeof(Object), typeof(Delegate) );
		}
        public void RemoveEventHandler( System.Object target, System.Delegate handler ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RemoveEventHandler), typeof(Object), typeof(Delegate) );
		}
        public System.Reflection.MethodInfo GetAddMethod( bool nonPublic ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetAddMethod), typeof(Boolean) );
            return default( System.Reflection.MethodInfo );

		}
        public System.Reflection.MethodInfo GetRaiseMethod( bool nonPublic ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetRaiseMethod), typeof(Boolean) );
            return default( System.Reflection.MethodInfo );

		}
        public System.Reflection.MethodInfo GetRemoveMethod( bool nonPublic ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetRemoveMethod), typeof(Boolean) );
            return default( System.Reflection.MethodInfo );

		}
        public System.Object[][] GetCustomAttributes( System.Type attributeType, bool inherit ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetCustomAttributes), typeof(Type), typeof(Boolean) );
            return default( System.Object[][] );

		}
        public System.Object[][] GetCustomAttributes( bool inherit ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetCustomAttributes), typeof(Boolean) );
            return default( System.Object[][] );

		}
        public bool IsDefined( System.Type attributeType, bool inherit ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsDefined), typeof(Type), typeof(Boolean) );
            return default( bool );

		}
    }
}