// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Runtime.InteropServices {
    public struct CONNECTDATA {

        internal System.Object pUnk;

        internal int dwCookie;

    }
}