// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices;

namespace System.Runtime.InteropServices {
    public enum CustomQueryInterfaceMode {
        Allow = 1,
        Ignore = 0
    }
}