// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Runtime.InteropServices {
    public class ErrorWrapper {

        public int ErrorCode { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ErrorCode));
				return default (Int32);
			}
		}
        public ErrorWrapper( int errorCode )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ErrorWrapper), typeof(Int32));
            }
        public ErrorWrapper( System.Object errorCode )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ErrorWrapper), typeof(Object));
            }
        public ErrorWrapper( System.Exception e )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ErrorWrapper), typeof(Exception));
            }
    }
}