// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices;

namespace System.Runtime.InteropServices {
    public struct FUNCDESC {

        internal int memid;

        internal System.IntPtr lprgscode;

        internal System.IntPtr lprgelemdescParam;

        internal System.Runtime.InteropServices.FUNCKIND funckind;

        internal System.Runtime.InteropServices.INVOKEKIND invkind;

        internal System.Runtime.InteropServices.CALLCONV callconv;

        internal System.Int16 cParams;

        internal System.Int16 cParamsOpt;

        internal System.Int16 oVft;

        internal System.Int16 cScodes;

        internal System.Runtime.InteropServices.ELEMDESC elemdescFunc;

        internal System.Int16 wFuncFlags;

    }
}