// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Runtime.InteropServices {
    public interface ICustomFactory {

        System.MarshalByRefObject CreateInstance( System.Type serverType );

    }
}