// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices;

namespace System.Runtime.InteropServices {
    public enum IDispatchImplType {
        SystemDefinedImpl = 0,
        InternalImpl = 1,
        CompatibleImpl = 2
    }
}