// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;

namespace System.Runtime.InteropServices {
    public class ImportedFromTypeLibAttribute: System.Attribute {

        internal string _val;

        public string Value { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Value));
				return default (String);
			}
		}
        public ImportedFromTypeLibAttribute( string tlbFile )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ImportedFromTypeLibAttribute), typeof(String));
            }
    }
}