// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime;

namespace System.Runtime.InteropServices {
    public class InterfaceTypeAttribute: System.Attribute {

        internal System.Runtime.InteropServices.ComInterfaceType _val;

        public System.Runtime.InteropServices.ComInterfaceType Value { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Value));
				return default (ComInterfaceType);
			}
		}
        public InterfaceTypeAttribute( System.Runtime.InteropServices.ComInterfaceType interfaceType )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InterfaceTypeAttribute), typeof(ComInterfaceType));
            }
        public InterfaceTypeAttribute( System.Int16 interfaceType )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InterfaceTypeAttribute), typeof(Int16));
            }
    }
}