// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices;
using System.Reflection;

namespace System.Runtime.InteropServices {
    public interface ITypeLibExporterNotifySink {

        void ReportEvent( System.Runtime.InteropServices.ExporterEventKind eventKind, int eventCode, string eventMsg );

        System.Object ResolveRef( System.Reflection.Assembly assembly );

    }
}