// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;
using System.Runtime;

namespace System.Runtime.InteropServices {
    public class MarshalAsAttribute: System.Attribute {

        public System.Runtime.InteropServices.UnmanagedType Value {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Value));
				return default (UnmanagedType);
			}
		}
        public MarshalAsAttribute( System.Int16 unmanagedType )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MarshalAsAttribute), typeof(Int16));
            }
        public MarshalAsAttribute( System.Runtime.InteropServices.UnmanagedType unmanagedType )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MarshalAsAttribute), typeof(UnmanagedType));
            }
        internal System.Runtime.InteropServices.MarshalAsAttribute Copy() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy) );
            return default( System.Runtime.InteropServices.MarshalAsAttribute );

		}
    }
}