// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices;
using System.Reflection;
using System.Threading;
using System.Runtime.InteropServices.ComTypes;
using System.Security;

namespace System.Runtime.InteropServices {
    public static class Marshal {
        public static int AddRef( System.IntPtr pUnk ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddRef), typeof(IntPtr) );
            return default( int );

		}
        public static bool AreComObjectsAvailableForCleanup() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AreComObjectsAvailableForCleanup) );
            return default( bool );

		}
        public static void CleanupUnusedObjectsInCurrentContext() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CleanupUnusedObjectsInCurrentContext) );
		}
        public static System.IntPtr AllocCoTaskMem( int cb ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AllocCoTaskMem), typeof(Int32) );
            return default( System.IntPtr );

		}
        public static System.IntPtr AllocHGlobal( System.IntPtr cb ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AllocHGlobal), typeof(IntPtr) );
            return default( System.IntPtr );

		}
        public static System.IntPtr AllocHGlobal( int cb ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AllocHGlobal), typeof(Int32) );
            return default( System.IntPtr );

		}
        public static System.Object BindToMoniker( string monikerName ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(BindToMoniker), typeof(String) );
            return default( System.Object );

		}
        public static void ChangeWrapperHandleStrength( System.Object otp, bool fIsWeak ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ChangeWrapperHandleStrength), typeof(Object), typeof(Boolean) );
		}
        internal static void copy_to_unmanaged( System.Array source, int startIndex, System.IntPtr destination, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(copy_to_unmanaged), typeof(Array), typeof(Int32), typeof(IntPtr), typeof(Int32) );
		}
        internal static void copy_from_unmanaged( System.IntPtr source, int startIndex, System.Array destination, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(copy_from_unmanaged), typeof(IntPtr), typeof(Int32), typeof(Array), typeof(Int32) );
		}
        public static void Copy( byte[] source, int startIndex, System.IntPtr destination, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(Byte[]), typeof(Int32), typeof(IntPtr), typeof(Int32) );
		}
        public static void Copy( char[] source, int startIndex, System.IntPtr destination, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(Char[]), typeof(Int32), typeof(IntPtr), typeof(Int32) );
		}
        public static void Copy( System.Int16[] source, int startIndex, System.IntPtr destination, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(Int16[]), typeof(Int32), typeof(IntPtr), typeof(Int32) );
		}
        public static void Copy( int[] source, int startIndex, System.IntPtr destination, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(Int32[]), typeof(Int32), typeof(IntPtr), typeof(Int32) );
		}
        public static void Copy( long[] source, int startIndex, System.IntPtr destination, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(Int64[]), typeof(Int32), typeof(IntPtr), typeof(Int32) );
		}
        public static void Copy( float[] source, int startIndex, System.IntPtr destination, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(Single[]), typeof(Int32), typeof(IntPtr), typeof(Int32) );
		}
        public static void Copy( double[] source, int startIndex, System.IntPtr destination, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(Double[]), typeof(Int32), typeof(IntPtr), typeof(Int32) );
		}
        public static void Copy( System.IntPtr[] source, int startIndex, System.IntPtr destination, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(IntPtr[]), typeof(Int32), typeof(IntPtr), typeof(Int32) );
		}
        public static void Copy( System.IntPtr source, byte[] destination, int startIndex, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(IntPtr), typeof(Byte[]), typeof(Int32), typeof(Int32) );
		}
        public static void Copy( System.IntPtr source, char[] destination, int startIndex, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(IntPtr), typeof(Char[]), typeof(Int32), typeof(Int32) );
		}
        public static void Copy( System.IntPtr source, System.Int16[] destination, int startIndex, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(IntPtr), typeof(Int16[]), typeof(Int32), typeof(Int32) );
		}
        public static void Copy( System.IntPtr source, int[] destination, int startIndex, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(IntPtr), typeof(Int32[]), typeof(Int32), typeof(Int32) );
		}
        public static void Copy( System.IntPtr source, long[] destination, int startIndex, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(IntPtr), typeof(Int64[]), typeof(Int32), typeof(Int32) );
		}
        public static void Copy( System.IntPtr source, float[] destination, int startIndex, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(IntPtr), typeof(Single[]), typeof(Int32), typeof(Int32) );
		}
        public static void Copy( System.IntPtr source, double[] destination, int startIndex, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(IntPtr), typeof(Double[]), typeof(Int32), typeof(Int32) );
		}
        public static void Copy( System.IntPtr source, System.IntPtr[] destination, int startIndex, int length ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy), typeof(IntPtr), typeof(IntPtr[]), typeof(Int32), typeof(Int32) );
		}
        public static System.IntPtr CreateAggregatedObject( System.IntPtr pOuter, System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateAggregatedObject), typeof(IntPtr), typeof(Object) );
            return default( System.IntPtr );

		}
        public static System.IntPtr CreateAggregatedObject<T>( System.IntPtr pOuter, T o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateAggregatedObject), typeof(IntPtr), typeof(T) );
            return default( System.IntPtr );

		}
        public static System.Object CreateWrapperOfType( System.Object o, System.Type t ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateWrapperOfType), typeof(Object), typeof(Type) );
            return default( System.Object );

		}
        public static TWrapper CreateWrapperOfType<T, TWrapper>( T o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateWrapperOfType), typeof(T) );
            return default( TWrapper );

		}
        public static void DestroyStructure( System.IntPtr ptr, System.Type structuretype ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DestroyStructure), typeof(IntPtr), typeof(Type) );
		}
        public static void DestroyStructure<T>( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DestroyStructure), typeof(IntPtr) );
		}
        public static void FreeBSTR( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FreeBSTR), typeof(IntPtr) );
		}
        public static void FreeCoTaskMem( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FreeCoTaskMem), typeof(IntPtr) );
		}
        public static void FreeHGlobal( System.IntPtr hglobal ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FreeHGlobal), typeof(IntPtr) );
		}
        public static void ZeroFreeBSTR( System.IntPtr s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ZeroFreeBSTR), typeof(IntPtr) );
		}
        public static void ZeroFreeCoTaskMemAnsi( System.IntPtr s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ZeroFreeCoTaskMemAnsi), typeof(IntPtr) );
		}
        public static void ZeroFreeCoTaskMemUnicode( System.IntPtr s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ZeroFreeCoTaskMemUnicode), typeof(IntPtr) );
		}
        public static void ZeroFreeCoTaskMemUTF8( System.IntPtr s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ZeroFreeCoTaskMemUTF8), typeof(IntPtr) );
		}
        public static void ZeroFreeGlobalAllocAnsi( System.IntPtr s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ZeroFreeGlobalAllocAnsi), typeof(IntPtr) );
		}
        public static void ZeroFreeGlobalAllocUnicode( System.IntPtr s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ZeroFreeGlobalAllocUnicode), typeof(IntPtr) );
		}
        public static System.Guid GenerateGuidForType( System.Type type ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GenerateGuidForType), typeof(Type) );
            return default( System.Guid );

		}
        public static string GenerateProgIdForType( System.Type type ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GenerateProgIdForType), typeof(Type) );
            return default( string );

		}
        public static System.Object GetActiveObject( string progID ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetActiveObject), typeof(String) );
            return default( System.Object );

		}
        public static System.IntPtr GetComInterfaceForObject( System.Object o, System.Type T ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetComInterfaceForObject), typeof(Object), typeof(Type) );
            return default( System.IntPtr );

		}
        public static System.IntPtr GetComInterfaceForObject( System.Object o, System.Type T, System.Runtime.InteropServices.CustomQueryInterfaceMode mode ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetComInterfaceForObject), typeof(Object), typeof(Type), typeof(CustomQueryInterfaceMode) );
            return default( System.IntPtr );

		}
        public static System.IntPtr GetComInterfaceForObject<T, TInterface>( T o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetComInterfaceForObject), typeof(T) );
            return default( System.IntPtr );

		}
        public static System.IntPtr GetComInterfaceForObjectInContext( System.Object o, System.Type t ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetComInterfaceForObjectInContext), typeof(Object), typeof(Type) );
            return default( System.IntPtr );

		}
        public static System.Object GetComObjectData( System.Object obj, System.Object key ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetComObjectData), typeof(Object), typeof(Object) );
            return default( System.Object );

		}
        public static int GetComSlotForMethodInfo( System.Reflection.MemberInfo m ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetComSlotForMethodInfo), typeof(MemberInfo) );
            return default( int );

		}
        public static int GetEndComSlot( System.Type t ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetEndComSlot), typeof(Type) );
            return default( int );

		}
        public static System.IntPtr GetExceptionPointers() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetExceptionPointers) );
            return default( System.IntPtr );

		}
        public static System.IntPtr GetHINSTANCE( System.Reflection.Module m ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHINSTANCE), typeof(Module) );
            return default( System.IntPtr );

		}
        public static int GetExceptionCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetExceptionCode) );
            return default( int );

		}
        public static int GetHRForException( System.Exception e ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHRForException), typeof(Exception) );
            return default( int );

		}
        public static int GetHRForLastWin32Error() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHRForLastWin32Error) );
            return default( int );

		}
        public static System.IntPtr GetIDispatchForObject( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetIDispatchForObject), typeof(Object) );
            return default( System.IntPtr );

		}
        public static System.IntPtr GetIDispatchForObjectInContext( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetIDispatchForObjectInContext), typeof(Object) );
            return default( System.IntPtr );

		}
        public static System.IntPtr GetITypeInfoForType( System.Type t ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetITypeInfoForType), typeof(Type) );
            return default( System.IntPtr );

		}
        public static System.IntPtr GetIUnknownForObjectInContext( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetIUnknownForObjectInContext), typeof(Object) );
            return default( System.IntPtr );

		}
        public static System.IntPtr GetManagedThunkForUnmanagedMethodPtr( System.IntPtr pfnMethodToWrap, System.IntPtr pbSignature, int cbSignature ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetManagedThunkForUnmanagedMethodPtr), typeof(IntPtr), typeof(IntPtr), typeof(Int32) );
            return default( System.IntPtr );

		}
        public static System.Reflection.MemberInfo GetMethodInfoForComSlot( System.Type t, int slot, ref System.Runtime.InteropServices.ComMemberType memberType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetMethodInfoForComSlot), typeof(Type), typeof(Int32), typeof(ComMemberType) );
            return default( System.Reflection.MemberInfo );

		}
        public static System.IntPtr GetIUnknownForObject( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetIUnknownForObject), typeof(Object) );
            return default( System.IntPtr );

		}
        public static void GetNativeVariantForObject( System.Object obj, System.IntPtr pDstNativeVariant ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetNativeVariantForObject), typeof(Object), typeof(IntPtr) );
		}
        public static void GetNativeVariantForObject<T>( T obj, System.IntPtr pDstNativeVariant ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetNativeVariantForObject), typeof(T), typeof(IntPtr) );
		}
        public static System.Object GetObjectForIUnknown( System.IntPtr pUnk ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetObjectForIUnknown), typeof(IntPtr) );
            return default( System.Object );

		}
        public static System.Object GetObjectForNativeVariant( System.IntPtr pSrcNativeVariant ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetObjectForNativeVariant), typeof(IntPtr) );
            return default( System.Object );

		}
        public static T GetObjectForNativeVariant<T>( System.IntPtr pSrcNativeVariant ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetObjectForNativeVariant), typeof(IntPtr) );
            return default( T );

		}
        public static System.Object[][] GetObjectsForNativeVariants( System.IntPtr aSrcNativeVariant, int cVars ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetObjectsForNativeVariants), typeof(IntPtr), typeof(Int32) );
            return default( System.Object[][] );

		}
        public static T[][] GetObjectsForNativeVariants<T>( System.IntPtr aSrcNativeVariant, int cVars ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetObjectsForNativeVariants), typeof(IntPtr), typeof(Int32) );
            return default( T[][] );

		}
        public static int GetStartComSlot( System.Type t ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetStartComSlot), typeof(Type) );
            return default( int );

		}
        public static System.Threading.Thread GetThreadFromFiberCookie( int cookie ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetThreadFromFiberCookie), typeof(Int32) );
            return default( System.Threading.Thread );

		}
        public static System.Object GetTypedObjectForIUnknown( System.IntPtr pUnk, System.Type t ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypedObjectForIUnknown), typeof(IntPtr), typeof(Type) );
            return default( System.Object );

		}
        public static System.Type GetTypeForITypeInfo( System.IntPtr piTypeInfo ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeForITypeInfo), typeof(IntPtr) );
            return default( System.Type );

		}
        public static string GetTypeInfoName( System.Runtime.InteropServices.UCOMITypeInfo pTI ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeInfoName), typeof(UCOMITypeInfo) );
            return default( string );

		}
        public static System.Guid GetTypeLibGuid( System.Runtime.InteropServices.UCOMITypeLib pTLB ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeLibGuid), typeof(UCOMITypeLib) );
            return default( System.Guid );

		}
        public static System.Guid GetTypeLibGuid( System.Runtime.InteropServices.ComTypes.ITypeLib typelib ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeLibGuid), typeof(ITypeLib) );
            return default( System.Guid );

		}
        public static System.Guid GetTypeLibGuidForAssembly( System.Reflection.Assembly asm ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeLibGuidForAssembly), typeof(Assembly) );
            return default( System.Guid );

		}
        public static int GetTypeLibLcid( System.Runtime.InteropServices.UCOMITypeLib pTLB ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeLibLcid), typeof(UCOMITypeLib) );
            return default( int );

		}
        public static int GetTypeLibLcid( System.Runtime.InteropServices.ComTypes.ITypeLib typelib ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeLibLcid), typeof(ITypeLib) );
            return default( int );

		}
        public static string GetTypeLibName( System.Runtime.InteropServices.UCOMITypeLib pTLB ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeLibName), typeof(UCOMITypeLib) );
            return default( string );

		}
        public static string GetTypeLibName( System.Runtime.InteropServices.ComTypes.ITypeLib typelib ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeLibName), typeof(ITypeLib) );
            return default( string );

		}
        public static void GetTypeLibVersionForAssembly( System.Reflection.Assembly inputAssembly, out System.Int32 majorVersion, out System.Int32 minorVersion ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeLibVersionForAssembly), typeof(Assembly), typeof(Int32), typeof(Int32) );
            majorVersion = default( System.Int32 ); minorVersion = default( System.Int32 );

		}
        public static System.IntPtr GetUnmanagedThunkForManagedMethodPtr( System.IntPtr pfnMethodToWrap, System.IntPtr pbSignature, int cbSignature ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetUnmanagedThunkForManagedMethodPtr), typeof(IntPtr), typeof(IntPtr), typeof(Int32) );
            return default( System.IntPtr );

		}
        public static bool IsTypeVisibleFromCom( System.Type t ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsTypeVisibleFromCom), typeof(Type) );
            return default( bool );

		}
        public static int NumParamBytes( System.Reflection.MethodInfo m ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(NumParamBytes), typeof(MethodInfo) );
            return default( int );

		}
        public static System.Type GetTypeFromCLSID( System.Guid clsid ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeFromCLSID), typeof(Guid) );
            return default( System.Type );

		}
        public static string GetTypeInfoName( System.Runtime.InteropServices.ComTypes.ITypeInfo typeInfo ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetTypeInfoName), typeof(ITypeInfo) );
            return default( string );

		}
        public static System.Object GetUniqueObjectForIUnknown( System.IntPtr unknown ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetUniqueObjectForIUnknown), typeof(IntPtr) );
            return default( System.Object );

		}
        public static bool IsComObject( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsComObject), typeof(Object) );
            return default( bool );

		}
        public static int GetLastWin32Error() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetLastWin32Error) );
            return default( int );

		}
        public static System.IntPtr OffsetOf( System.Type t, string fieldName ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OffsetOf), typeof(Type), typeof(String) );
            return default( System.IntPtr );

		}
        public static System.IntPtr OffsetOf<T>( string fieldName ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OffsetOf), typeof(String) );
            return default( System.IntPtr );

		}
        public static void Prelink( System.Reflection.MethodInfo m ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Prelink), typeof(MethodInfo) );
		}
        public static void PrelinkAll( System.Type c ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PrelinkAll), typeof(Type) );
		}
        public static string PtrToStringAnsi( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStringAnsi), typeof(IntPtr) );
            return default( string );

		}
        public static string PtrToStringAnsi( System.IntPtr ptr, int len ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStringAnsi), typeof(IntPtr), typeof(Int32) );
            return default( string );

		}
        public static string PtrToStringUTF8( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStringUTF8), typeof(IntPtr) );
            return default( string );

		}
        public static string PtrToStringUTF8( System.IntPtr ptr, int byteLen ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStringUTF8), typeof(IntPtr), typeof(Int32) );
            return default( string );

		}
        public static string PtrToStringAuto( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStringAuto), typeof(IntPtr) );
            return default( string );

		}
        public static string PtrToStringAuto( System.IntPtr ptr, int len ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStringAuto), typeof(IntPtr), typeof(Int32) );
            return default( string );

		}
        public static string PtrToStringUni( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStringUni), typeof(IntPtr) );
            return default( string );

		}
        public static string PtrToStringUni( System.IntPtr ptr, int len ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStringUni), typeof(IntPtr), typeof(Int32) );
            return default( string );

		}
        public static string PtrToStringBSTR( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStringBSTR), typeof(IntPtr) );
            return default( string );

		}
        public static void PtrToStructure( System.IntPtr ptr, System.Object structure ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStructure), typeof(IntPtr), typeof(Object) );
		}
        public static System.Object PtrToStructure( System.IntPtr ptr, System.Type structureType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStructure), typeof(IntPtr), typeof(Type) );
            return default( System.Object );

		}
        public static void PtrToStructure<T>( System.IntPtr ptr, T structure ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStructure), typeof(IntPtr), typeof(T) );
		}
        public static T PtrToStructure<T>( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PtrToStructure), typeof(IntPtr) );
            return default( T );

		}
        public static int QueryInterface( System.IntPtr pUnk, ref System.Guid iid, out System.IntPtr ppv ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(QueryInterface), typeof(IntPtr), typeof(Guid), typeof(IntPtr) );
            ppv = default( System.IntPtr );

            return default( int );

		}
        public static byte ReadByte( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadByte), typeof(IntPtr) );
            return default( byte );

		}
        public static byte ReadByte( System.IntPtr ptr, int ofs ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadByte), typeof(IntPtr), typeof(Int32) );
            return default( byte );

		}
        public static byte ReadByte( System.Object ptr, int ofs ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadByte), typeof(Object), typeof(Int32) );
            return default( byte );

		}
        public static System.Int16 ReadInt16( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadInt16), typeof(IntPtr) );
            return default( System.Int16 );

		}
        public static System.Int16 ReadInt16( System.IntPtr ptr, int ofs ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadInt16), typeof(IntPtr), typeof(Int32) );
            return default( System.Int16 );

		}
        public static System.Int16 ReadInt16( System.Object ptr, int ofs ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadInt16), typeof(Object), typeof(Int32) );
            return default( System.Int16 );

		}
        public static int ReadInt32( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadInt32), typeof(IntPtr) );
            return default( int );

		}
        public static int ReadInt32( System.IntPtr ptr, int ofs ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadInt32), typeof(IntPtr), typeof(Int32) );
            return default( int );

		}
        public static int ReadInt32( System.Object ptr, int ofs ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadInt32), typeof(Object), typeof(Int32) );
            return default( int );

		}
        public static long ReadInt64( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadInt64), typeof(IntPtr) );
            return default( long );

		}
        public static long ReadInt64( System.IntPtr ptr, int ofs ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadInt64), typeof(IntPtr), typeof(Int32) );
            return default( long );

		}
        public static long ReadInt64( System.Object ptr, int ofs ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadInt64), typeof(Object), typeof(Int32) );
            return default( long );

		}
        public static System.IntPtr ReadIntPtr( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadIntPtr), typeof(IntPtr) );
            return default( System.IntPtr );

		}
        public static System.IntPtr ReadIntPtr( System.IntPtr ptr, int ofs ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadIntPtr), typeof(IntPtr), typeof(Int32) );
            return default( System.IntPtr );

		}
        public static System.IntPtr ReadIntPtr( System.Object ptr, int ofs ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadIntPtr), typeof(Object), typeof(Int32) );
            return default( System.IntPtr );

		}
        public static System.IntPtr ReAllocCoTaskMem( System.IntPtr pv, int cb ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReAllocCoTaskMem), typeof(IntPtr), typeof(Int32) );
            return default( System.IntPtr );

		}
        public static System.IntPtr ReAllocHGlobal( System.IntPtr pv, System.IntPtr cb ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReAllocHGlobal), typeof(IntPtr), typeof(IntPtr) );
            return default( System.IntPtr );

		}
        public static int Release( System.IntPtr pUnk ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Release), typeof(IntPtr) );
            return default( int );

		}
        public static int ReleaseComObject( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReleaseComObject), typeof(Object) );
            return default( int );

		}
        public static void ReleaseThreadCache() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReleaseThreadCache) );
		}
        public static bool SetComObjectData( System.Object obj, System.Object key, System.Object data ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetComObjectData), typeof(Object), typeof(Object), typeof(Object) );
            return default( bool );

		}
        public static int SizeOf( System.Object structure ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SizeOf), typeof(Object) );
            return default( int );

		}
        public static int SizeOf( System.Type t ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SizeOf), typeof(Type) );
            return default( int );

		}
        public static int SizeOf<T>() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SizeOf) );
            return default( int );

		}
        public static int SizeOf<T>( T structure ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SizeOf), typeof(T) );
            return default( int );

		}
        internal static int SizeOfType( System.Type type ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SizeOfType), typeof(Type) );
            return default( int );

		}
        internal static int AlignedSizeOf<T>()
            where T : struct {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AlignedSizeOf) );
            return default( int );

		}
        public static System.IntPtr StringToBSTR( string s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StringToBSTR), typeof(String) );
            return default( System.IntPtr );

		}
        public static System.IntPtr StringToCoTaskMemAnsi( string s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StringToCoTaskMemAnsi), typeof(String) );
            return default( System.IntPtr );

		}
        public static System.IntPtr StringToCoTaskMemAuto( string s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StringToCoTaskMemAuto), typeof(String) );
            return default( System.IntPtr );

		}
        public static System.IntPtr StringToCoTaskMemUni( string s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StringToCoTaskMemUni), typeof(String) );
            return default( System.IntPtr );

		}
        public static System.IntPtr StringToHGlobalAnsi( string s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StringToHGlobalAnsi), typeof(String) );
            return default( System.IntPtr );

		}
        public static System.IntPtr StringToAllocatedMemoryUTF8( string s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StringToAllocatedMemoryUTF8), typeof(String) );
            return default( System.IntPtr );

		}
        public static System.IntPtr StringToHGlobalAuto( string s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StringToHGlobalAuto), typeof(String) );
            return default( System.IntPtr );

		}
        public static System.IntPtr StringToHGlobalUni( string s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StringToHGlobalUni), typeof(String) );
            return default( System.IntPtr );

		}
        public static System.IntPtr SecureStringToBSTR( System.Security.SecureString s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SecureStringToBSTR), typeof(SecureString) );
            return default( System.IntPtr );

		}
        public static System.IntPtr SecureStringToCoTaskMemAnsi( System.Security.SecureString s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SecureStringToCoTaskMemAnsi), typeof(SecureString) );
            return default( System.IntPtr );

		}
        public static System.IntPtr SecureStringToCoTaskMemUnicode( System.Security.SecureString s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SecureStringToCoTaskMemUnicode), typeof(SecureString) );
            return default( System.IntPtr );

		}
        public static System.IntPtr SecureStringToGlobalAllocAnsi( System.Security.SecureString s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SecureStringToGlobalAllocAnsi), typeof(SecureString) );
            return default( System.IntPtr );

		}
        public static System.IntPtr SecureStringToGlobalAllocUnicode( System.Security.SecureString s ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SecureStringToGlobalAllocUnicode), typeof(SecureString) );
            return default( System.IntPtr );

		}
        public static void StructureToPtr( System.Object structure, System.IntPtr ptr, bool fDeleteOld ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StructureToPtr), typeof(Object), typeof(IntPtr), typeof(Boolean) );
		}
        public static void StructureToPtr<T>( T structure, System.IntPtr ptr, bool fDeleteOld ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(StructureToPtr), typeof(T), typeof(IntPtr), typeof(Boolean) );
		}
        public static void ThrowExceptionForHR( int errorCode ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ThrowExceptionForHR), typeof(Int32) );
		}
        public static void ThrowExceptionForHR( int errorCode, System.IntPtr errorInfo ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ThrowExceptionForHR), typeof(Int32), typeof(IntPtr) );
		}
        public static System.IntPtr UnsafeAddrOfPinnedArrayElement( System.Array arr, int index ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UnsafeAddrOfPinnedArrayElement), typeof(Array), typeof(Int32) );
            return default( System.IntPtr );

		}
        public static System.IntPtr UnsafeAddrOfPinnedArrayElement<T>( T[] arr, int index ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UnsafeAddrOfPinnedArrayElement), typeof(T[]), typeof(Int32) );
            return default( System.IntPtr );

		}
        public static void WriteByte( System.IntPtr ptr, byte val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteByte), typeof(IntPtr), typeof(Byte) );
		}
        public static void WriteByte( System.IntPtr ptr, int ofs, byte val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteByte), typeof(IntPtr), typeof(Int32), typeof(Byte) );
		}
        public static void WriteByte( [System.Runtime.InteropServices.InAttribute, System.Runtime.InteropServices.OutAttribute] System.Object ptr, int ofs, byte val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteByte), typeof(Object), typeof(Int32), typeof(Byte) );
            ptr = default( System.Object );

		}
        public static void WriteInt16( System.IntPtr ptr, System.Int16 val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt16), typeof(IntPtr), typeof(Int16) );
		}
        public static void WriteInt16( System.IntPtr ptr, int ofs, System.Int16 val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt16), typeof(IntPtr), typeof(Int32), typeof(Int16) );
		}
        public static void WriteInt16( [System.Runtime.InteropServices.InAttribute, System.Runtime.InteropServices.OutAttribute] System.Object ptr, int ofs, System.Int16 val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt16), typeof(Object), typeof(Int32), typeof(Int16) );
            ptr = default( System.Object );

		}
        public static void WriteInt16( System.IntPtr ptr, char val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt16), typeof(IntPtr), typeof(Char) );
		}
        public static void WriteInt16( System.IntPtr ptr, int ofs, char val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt16), typeof(IntPtr), typeof(Int32), typeof(Char) );
		}
        public static void WriteInt16( [System.Runtime.InteropServices.InAttribute, System.Runtime.InteropServices.OutAttribute] System.Object ptr, int ofs, char val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt16), typeof(Object), typeof(Int32), typeof(Char) );
            ptr = default( System.Object );

		}
        public static void WriteInt32( System.IntPtr ptr, int val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt32), typeof(IntPtr), typeof(Int32) );
		}
        public static void WriteInt32( System.IntPtr ptr, int ofs, int val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt32), typeof(IntPtr), typeof(Int32), typeof(Int32) );
		}
        public static void WriteInt32( [System.Runtime.InteropServices.InAttribute, System.Runtime.InteropServices.OutAttribute] System.Object ptr, int ofs, int val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt32), typeof(Object), typeof(Int32), typeof(Int32) );
            ptr = default( System.Object );

		}
        public static void WriteInt64( System.IntPtr ptr, long val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt64), typeof(IntPtr), typeof(Int64) );
		}
        public static void WriteInt64( System.IntPtr ptr, int ofs, long val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt64), typeof(IntPtr), typeof(Int32), typeof(Int64) );
		}
        public static void WriteInt64( [System.Runtime.InteropServices.InAttribute, System.Runtime.InteropServices.OutAttribute] System.Object ptr, int ofs, long val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt64), typeof(Object), typeof(Int32), typeof(Int64) );
            ptr = default( System.Object );

		}
        public static void WriteIntPtr( System.IntPtr ptr, System.IntPtr val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteIntPtr), typeof(IntPtr), typeof(IntPtr) );
		}
        public static void WriteIntPtr( System.IntPtr ptr, int ofs, System.IntPtr val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteIntPtr), typeof(IntPtr), typeof(Int32), typeof(IntPtr) );
		}
        public static void WriteIntPtr( [System.Runtime.InteropServices.InAttribute, System.Runtime.InteropServices.OutAttribute] System.Object ptr, int ofs, System.IntPtr val ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteIntPtr), typeof(Object), typeof(Int32), typeof(IntPtr) );
            ptr = default( System.Object );

		}
        public static System.Exception GetExceptionForHR( int errorCode ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetExceptionForHR), typeof(Int32) );
            return default( System.Exception );

		}
        public static System.Exception GetExceptionForHR( int errorCode, System.IntPtr errorInfo ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetExceptionForHR), typeof(Int32), typeof(IntPtr) );
            return default( System.Exception );

		}
        public static int FinalReleaseComObject( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FinalReleaseComObject), typeof(Object) );
            return default( int );

		}
        public static System.Delegate GetDelegateForFunctionPointer( System.IntPtr ptr, System.Type t ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetDelegateForFunctionPointer), typeof(IntPtr), typeof(Type) );
            return default( System.Delegate );

		}
        public static TDelegate GetDelegateForFunctionPointer<TDelegate>( System.IntPtr ptr ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetDelegateForFunctionPointer), typeof(IntPtr) );
            return default( TDelegate );

		}
        public static System.IntPtr GetFunctionPointerForDelegate( System.Delegate d ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetFunctionPointerForDelegate), typeof(Delegate) );
            return default( System.IntPtr );

		}
        public static System.IntPtr GetFunctionPointerForDelegate<TDelegate>( TDelegate d ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetFunctionPointerForDelegate), typeof(TDelegate) );
            return default( System.IntPtr );

		}
        internal static void SetLastWin32Error( int error ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetLastWin32Error), typeof(Int32) );
		}
        internal static System.IntPtr GetRawIUnknownForComObjectNoAddRef( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetRawIUnknownForComObjectNoAddRef), typeof(Object) );
            return default( System.IntPtr );

		}
        internal static int GetHRForException_WinRT( System.Exception e ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHRForException_WinRT), typeof(Exception) );
            return default( int );

		}
        internal static System.Object GetNativeActivationFactory( System.Type type ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetNativeActivationFactory), typeof(Type) );
            return default( System.Object );

		}
    }
}