// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices;
using System.Runtime;

namespace System.Runtime.InteropServices {
    public static class RuntimeInformation {

        public static string FrameworkDescription { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FrameworkDescription));
				return default (String);
			}
		}
        public static string OSDescription { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OSDescription));
				return default (String);
			}
		}
        public static System.Runtime.InteropServices.Architecture OSArchitecture { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OSArchitecture));
				return default (Architecture);
			}
		}
        public static System.Runtime.InteropServices.Architecture ProcessArchitecture { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ProcessArchitecture));
				return default (Architecture);
			}
		}
        public static bool IsOSPlatform( System.Runtime.InteropServices.OSPlatform osPlatform ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsOSPlatform), typeof(OSPlatform) );
            return default( bool );
        
		}
    }
}