// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices;

namespace System.Runtime.InteropServices {
    public struct TYPEATTR {

        internal const int MEMBER_ID_NIL = -1;

        internal System.Guid guid;

        internal int lcid;

        internal int dwReserved;

        internal int memidConstructor;

        internal int memidDestructor;

        internal System.IntPtr lpstrSchema;

        internal int cbSizeInstance;

        internal System.Runtime.InteropServices.TYPEKIND typekind;

        internal System.Int16 cFuncs;

        internal System.Int16 cVars;

        internal System.Int16 cImplTypes;

        internal System.Int16 cbSizeVft;

        internal System.Int16 cbAlignment;

        internal System.Runtime.InteropServices.TYPEFLAGS wTypeFlags;

        internal System.Int16 wMajorVerNum;

        internal System.Int16 wMinorVerNum;

        internal System.Runtime.InteropServices.TYPEDESC tdescAlias;

        internal System.Runtime.InteropServices.IDLDESC idldescType;

    }
}