// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices;

namespace System.Runtime.InteropServices {
    public interface UCOMIStream {

        void Read( out byte[] pv, int cb, System.IntPtr pcbRead );

        void Write( byte[] pv, int cb, System.IntPtr pcbWritten );

        void Seek( long dlibMove, int dwOrigin, System.IntPtr plibNewPosition );

        void SetSize( long libNewSize );

        void CopyTo( System.Runtime.InteropServices.UCOMIStream pstm, long cb, System.IntPtr pcbRead, System.IntPtr pcbWritten );

        void Commit( int grfCommitFlags );

        void Revert();

        void LockRegion( long libOffset, long cb, int dwLockType );

        void UnlockRegion( long libOffset, long cb, int dwLockType );

        void Stat( out System.Runtime.InteropServices.STATSTG pstatstg, int grfStatFlag );

        void Clone( out System.Runtime.InteropServices.UCOMIStream ppstm );

    }
}