// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Configuration;
using System;

namespace System.Net.Configuration {
    public class HttpWebRequestElement {

        public int MaximumErrorResponseLength { get; set; }
        public int MaximumResponseHeadersLength { get; set; }
        public int MaximumUnauthorizedUploadLength { get; set; }
        public bool UseUnsafeHeaderParsing { get; set; }
        protected void PostDeserialize() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PostDeserialize) );
		}
    }
}