// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Configuration;
using System;

namespace System.Net.Configuration {
    public class ModuleElement {

        public string Type { get; set; }
    }
}