// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Configuration;
using System.Net.Configuration;
using System;
using System.Net;

namespace System.Net.Configuration {
    public class WebRequestModulesSection {

        protected void PostDeserialize() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PostDeserialize) );
		}
        protected void InitializeDefault() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InitializeDefault) );
		}
    }
}