// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Reflection;
using System;

namespace System.Reflection {
    public class AssemblyFlagsAttribute: System.Attribute {

        public int Flags {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Flags));
				return default (int);
			}
		}
        public int AssemblyFlags {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AssemblyFlags));
				return default (Int32);
			}
		}
        public AssemblyFlagsAttribute( int assemblyFlags )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AssemblyFlagsAttribute), typeof(Int32));
            }
        public AssemblyFlagsAttribute( System.Reflection.AssemblyNameFlags assemblyFlags )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AssemblyFlagsAttribute), typeof(AssemblyNameFlags));
            }
    }
}