// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;

namespace System.Reflection {
    public class AssemblyKeyNameAttribute: System.Attribute {

        public string KeyName { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(KeyName));
				return default (String);
			}
		}
        public AssemblyKeyNameAttribute( string keyName )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AssemblyKeyNameAttribute), typeof(String));
            }
    }
}