// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.Serialization;
using System;

namespace System.Reflection {
    public class Pointer: System.Runtime.Serialization.ISerializable {

        internal System.Object GetPointerValue() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetPointerValue) );
            return default( System.Object );

		}
    }
}