// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Permissions;

namespace System.Security.Permissions {
    public enum FileDialogPermissionAccess {
        None = 0,
        Open = 1,
        Save = 2,
        OpenSave = 3
    }
}