// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;
using System.Security;

namespace System.Security.Permissions {
    public class PrincipalPermissionAttribute: System.Security.Permissions.CodeAccessSecurityAttribute {

        public bool Authenticated { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public PrincipalPermissionAttribute( System.Security.Permissions.SecurityAction action )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PrincipalPermissionAttribute));
            }
        public System.Security.IPermission CreatePermission() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreatePermission) );
            return default( System.Security.IPermission );

		}
    }
}