// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security;
using System.Security.Permissions;
using System;

namespace System.Security.Permissions {
    public class UrlIdentityPermission: System.Security.CodeAccessPermission {

        public string Url { get; set; }
        public UrlIdentityPermission( System.Security.Permissions.PermissionState state )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UrlIdentityPermission), typeof(PermissionState));
            }
        public UrlIdentityPermission( string site )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UrlIdentityPermission), typeof(String));
            }
        public override System.Security.IPermission Copy() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy) );
            return default( System.Security.IPermission );

		}
        public override void FromXml( System.Security.SecurityElement esd ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FromXml), typeof(SecurityElement) );
		}
        public override System.Security.IPermission Intersect( System.Security.IPermission target ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Intersect), typeof(IPermission) );
            return default( System.Security.IPermission );

		}
        public override bool IsSubsetOf( System.Security.IPermission target ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsSubsetOf), typeof(IPermission) );
            return default( bool );

		}
        public override System.Security.SecurityElement ToXml() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToXml) );
            return default( System.Security.SecurityElement );

		}
        public override System.Security.IPermission Union( System.Security.IPermission target ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Union), typeof(IPermission) );
            return default( System.Security.IPermission );

		}
    }
}