// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections;
using System.Linq.Expressions;
using System;
using System.Linq;

namespace System.Linq {
    public interface IQueryable: System.Collections.IEnumerable {

        System.Linq.Expressions.Expression Expression { get; }

        System.Type ElementType { get; }

        System.Linq.IQueryProvider Provider { get; }
    }
}