// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Linq;
using System.Linq.Expressions;
using System;

namespace System.Linq {
    public interface IQueryProvider {

        System.Linq.IQueryable CreateQuery( System.Linq.Expressions.Expression expression );

        System.Linq.IQueryable<TElement> CreateQuery<TElement>( System.Linq.Expressions.Expression expression );

        System.Object Execute( System.Linq.Expressions.Expression expression );

        TResult Execute<TResult>( System.Linq.Expressions.Expression expression );

    }
}