// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections;
using System.Linq;

namespace System.Linq {
    public class ParallelQuery: System.Collections.IEnumerable {

        internal virtual System.Linq.ParallelQuery<TCastTo> Cast<TCastTo>() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Cast) );
            return default( System.Linq.ParallelQuery<TCastTo> );

		}
        internal virtual System.Linq.ParallelQuery<TCastTo> OfType<TCastTo>() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OfType) );
            return default( System.Linq.ParallelQuery<TCastTo> );

		}
        internal virtual System.Collections.IEnumerator GetEnumeratorUntyped() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetEnumeratorUntyped) );
            return default( System.Collections.IEnumerator );

		}
        System.Collections.IEnumerator @System.Collections.IEnumerable.GetEnumerator() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(@System.Collections.IEnumerable.GetEnumerator) );
            return default( System.Collections.IEnumerator );

		}
    }
}