// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Net.Sockets;

namespace System.Net.Sockets {
    public enum SocketShutdown {
        Receive = 0,
        Send = 1,
        Both = 2
    }
}