// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System.Net;
using System;
using System.Net.Sockets;

namespace System.Net.Sockets {
    public class SocketException: System.ComponentModel.Win32Exception {

        public int ErrorCode {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ErrorCode));
				return default (Int32);
			}
		}
        public string Message {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Message));
				return default (String);
			}
		}
        public System.Net.Sockets.SocketError SocketErrorCode {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SocketErrorCode));
				return default (SocketError);
			}
		}
        public SocketException(  ) : base( default( int ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SocketException));
            }
        public SocketException( int errorCode ) : base( default( int ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SocketException), typeof(Int32));
            }
    }
}