// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Net.Sockets;
using System.Net;

namespace System.Net.Sockets {
    public struct SocketReceiveMessageFromResult {

        internal int ReceivedBytes;

        internal System.Net.Sockets.SocketFlags SocketFlags;

        internal System.Net.EndPoint RemoteEndPoint;

        internal System.Net.Sockets.IPPacketInformation PacketInformation;

    }
}