// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER


namespace System.Text.RegularExpressions {
    public abstract class RegexRunnerFactory {

        internal abstract System.Text.RegularExpressions.RegexRunner CreateInstance();

    }
}