// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Configuration.Assemblies;
using System.Configuration;

namespace System.Configuration.Assemblies {
    public struct AssemblyHash: System.ICloneable {

        public System.Configuration.Assemblies.AssemblyHashAlgorithm Algorithm { get; set; }
        public AssemblyHash( System.Configuration.Assemblies.AssemblyHashAlgorithm algorithm, byte[] value )
        {
            Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AssemblyHash), typeof(AssemblyHashAlgorithm), typeof(Byte[]));
            Algorithm = AssemblyHashAlgorithm.None;
        }
        public AssemblyHash( byte[] value )
        {
            Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AssemblyHash), typeof(Byte[]));

            Algorithm = AssemblyHashAlgorithm.None;
        }
        public System.Object Clone() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Clone) );
            return default( System.Object );

		}
        public byte[][] GetValue() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetValue) );
            return default( byte[][] );

		}
        public void SetValue( byte[] value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetValue), typeof(Byte[]) );
		}
    }
}