// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Runtime.Hosting {
    public class ActivationArguments: System.Security.Policy.EvidenceBase {

        public System.ActivationContext ActivationContext {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ActivationContext));
				return default (ActivationContext);
			}
		}
        public string[][] ActivationData {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ActivationData));
				return default (String[][]);
			}
		}
        public System.ApplicationIdentity ApplicationIdentity {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ApplicationIdentity));
				return default (ApplicationIdentity);
			}
		}
        public ActivationArguments( System.ActivationContext activationData )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ActivationArguments), typeof(ActivationContext));
            }
        public ActivationArguments( System.ApplicationIdentity applicationIdentity )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ActivationArguments), typeof(ApplicationIdentity));
            }
        public ActivationArguments( System.ActivationContext activationContext, string[] activationData )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ActivationArguments), typeof(ActivationContext), typeof(String[]));
            }
        public ActivationArguments( System.ApplicationIdentity applicationIdentity, string[] activationData )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ActivationArguments), typeof(ApplicationIdentity), typeof(String[]));
            }
    }
}