// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Net.Mime {
    public static class Image {

        internal const string Gif = "image/gif";

        internal const string Tiff = "image/tiff";

        internal const string Jpeg = "image/jpeg";

    }
}