// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Runtime;

namespace System.Runtime.Versioning {
    public class ComponentGuaranteesAttribute: System.Attribute {

        public System.Runtime.Versioning.ComponentGuaranteesOptions Guarantees { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Guarantees));
				return default (ComponentGuaranteesOptions);
			}
		}
        public ComponentGuaranteesAttribute( System.Runtime.Versioning.ComponentGuaranteesOptions guarantees )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ComponentGuaranteesAttribute), typeof(ComponentGuaranteesOptions));
            }
    }
}