// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.Versioning;

namespace System.Runtime.Versioning {
    public class FrameworkName: System.IEquatable<System.Runtime.Versioning.FrameworkName> {

        public string Identifier { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Identifier));
				return default (String);
			}
		}
        public System.Version Version { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Version));
				return default (Version);
			}
		}
        public string Profile { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Profile));
				return default (String);
			}
		}
        public string FullName { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FullName));
				return default (String);
			}
		}
        public FrameworkName( string identifier, System.Version version )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FrameworkName), typeof(String), typeof(Version));
            }
        public FrameworkName( string identifier, System.Version version, string profile )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FrameworkName), typeof(String), typeof(Version), typeof(String));
            }
        public FrameworkName( string frameworkName )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FrameworkName), typeof(String));
            }
        public override bool Equals( System.Object obj ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );
        
		}
        public bool Equals( System.Runtime.Versioning.FrameworkName other ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(FrameworkName) );
            return default( bool );
        
		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );
        
		}
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );
        
		}
    }
}