// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Runtime.Remoting {
    public interface IChannelInfo {

        System.Object[][] ChannelData { get; set; }
    }
}