// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.Remoting;
using System;

namespace System.Runtime.Remoting {
    public class ObjectHandle: System.MarshalByRefObject, System.Runtime.Remoting.IObjectHandle {

        public ObjectHandle( System.Object o )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ObjectHandle), typeof(Object));
            }
        public override System.Object InitializeLifetimeService() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InitializeLifetimeService) );
            return default( System.Object );
        
		}
        public System.Object Unwrap() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Unwrap) );
            return default( System.Object );
        
		}
    }
}