// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Collections;
using System.Security.AccessControl;
using System;
using System.Security;

namespace System.Security.AccessControl {
    public class AceEnumerator: System.Collections.IEnumerator {

        public System.Security.AccessControl.GenericAce Current {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Current));
				return default (GenericAce);
			}
		}
        System.Object @System.Collections.IEnumerator.Current {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(System.Collections.IEnumerator.Current));
				return default (Object);
			}
		}
        public bool MoveNext() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MoveNext) );
            return default( bool );

		}
        public void Reset() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Reset) );
		}
        
    }
}