// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.AccessControl;

namespace System.Security.AccessControl {
    public enum AceQualifier {
        AccessAllowed = 0,
        AccessDenied = 1,
        SystemAudit = 2,
        SystemAlarm = 3
    }
}