// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.Principal;

namespace System.Security.AccessControl {
    public class CommonAce: System.Security.AccessControl.QualifiedAce {

        public override int BinaryLength {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(BinaryLength));
				return default (Int32);
			}
		}
        public CommonAce( System.Security.AccessControl.AceFlags flags, System.Security.AccessControl.AceQualifier qualifier, int accessMask, System.Security.Principal.SecurityIdentifier sid, bool isCallback, byte[] opaque )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CommonAce), typeof(AceFlags), typeof(AceQualifier), typeof(Int32), typeof(SecurityIdentifier), typeof(Boolean), typeof(Byte[]));
            }
        public override void GetBinaryForm( byte[] binaryForm, int offset ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetBinaryForm), typeof(Byte[]), typeof(Int32) );
		}
        public static int MaxOpaqueLength( bool isCallback ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MaxOpaqueLength), typeof(Boolean) );
            return default( int );

		}
        internal override string GetSddlForm() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetSddlForm) );
            return default( string );

		}
    }
}