// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security.AccessControl;

namespace System.Security.AccessControl {
    public enum EventWaitHandleRights {
        Modify = 2,
        Delete = 65536,
        ReadPermissions = 131072,
        ChangePermissions = 262144,
        TakeOwnership = 524288,
        Synchronize = 1048576,
        FullControl = 2031619
    }
}