// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security.AccessControl;
using System;
using System.Security;

namespace System.Security.AccessControl {
    public abstract class GenericAce {

        public System.Security.AccessControl.AceFlags AceFlags { get; set; }
        public System.Security.AccessControl.AceType AceType {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AceType));
				return default (AceType);
			}
		}
        public System.Security.AccessControl.AuditFlags AuditFlags {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AuditFlags));
				return default (AuditFlags);
			}
		}
        public abstract int BinaryLength { get; }

        public System.Security.AccessControl.InheritanceFlags InheritanceFlags {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InheritanceFlags));
				return default (InheritanceFlags);
			}
		}
        public bool IsInherited {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsInherited));
				return default (Boolean);
			}
		}
        public System.Security.AccessControl.PropagationFlags PropagationFlags {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PropagationFlags));
				return default (PropagationFlags);
			}
		}
        public System.Security.AccessControl.GenericAce Copy() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Copy) );
            return default( System.Security.AccessControl.GenericAce );

		}
        public static System.Security.AccessControl.GenericAce CreateFromBinaryForm( byte[] binaryForm, int offset ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateFromBinaryForm), typeof(Byte[]), typeof(Int32) );
            return default( System.Security.AccessControl.GenericAce );

		}
        public override bool Equals( System.Object o ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public abstract void GetBinaryForm( byte[] binaryForm, int offset );

        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
        internal abstract string GetSddlForm();

        internal static System.Security.AccessControl.GenericAce CreateFromSddlForm( string sddlForm, ref System.Int32 pos ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateFromSddlForm), typeof(String), typeof(Int32) );
            return default( System.Security.AccessControl.GenericAce );

		}
        internal static string GetSddlAceType( System.Security.AccessControl.AceType type ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetSddlAceType), typeof(AceType) );
            return default( string );

		}
        internal static string GetSddlAceFlags( System.Security.AccessControl.AceFlags flags ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetSddlAceFlags), typeof(AceFlags) );
            return default( string );

		}
        internal static short  ReadUShort( byte[] buffer, int offset ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadUShort), typeof(Byte[]), typeof(Int32) );
            return default( short  );

		}
        internal static int ReadInt( byte[] buffer, int offset ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadInt), typeof(Byte[]), typeof(Int32) );
            return default( int );

		}
        internal static void WriteInt( int val, byte[] buffer, int offset ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteInt), typeof(Int32), typeof(Byte[]), typeof(Int32) );
		}
        internal static void WriteUShort( short  val, byte[] buffer, int offset ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WriteUShort), typeof(short), typeof(Byte[]), typeof(Int32) );
		}
    }
}