// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Runtime.InteropServices;
using System.Security.AccessControl;
using System.Security.Principal;

namespace System.Security.AccessControl {
    public abstract class ObjectSecurity<T>: System.Security.AccessControl.NativeObjectSecurity    where T : struct {

        public override System.Type AccessRightType {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AccessRightType));
				return default (Type);
			}
		}
        public override System.Type AccessRuleType {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AccessRuleType));
				return default (Type);
			}
		}
        public override System.Type AuditRuleType {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AuditRuleType));
				return default (Type);
			}
		}
        public override System.Security.AccessControl.AccessRule AccessRuleFactory( System.Security.Principal.IdentityReference identityReference, int accessMask, bool isInherited, System.Security.AccessControl.InheritanceFlags inheritanceFlags, System.Security.AccessControl.PropagationFlags propagationFlags, System.Security.AccessControl.AccessControlType type ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AccessRuleFactory), typeof(IdentityReference), typeof(Int32), typeof(Boolean), typeof(InheritanceFlags), typeof(PropagationFlags), typeof(AccessControlType) );
            return default( System.Security.AccessControl.AccessRule );

		}
        public virtual void AddAccessRule( AccessRule<T> rule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddAccessRule), typeof(AccessRule<T>) );
		}
        public virtual bool RemoveAccessRule( AccessRule<T> rule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RemoveAccessRule), typeof(AccessRule<T>) );
            return default( bool );

		}
        public virtual void RemoveAccessRuleAll( AccessRule<T> rule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RemoveAccessRuleAll), typeof(AccessRule<T>) );
		}
        public virtual void RemoveAccessRuleSpecific( AccessRule<T> rule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RemoveAccessRuleSpecific), typeof(AccessRule<T>) );
		}
        public virtual void ResetAccessRule( AccessRule<T> rule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ResetAccessRule), typeof(AccessRule<T>) );
		}
        public virtual void SetAccessRule( AccessRule<T> rule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetAccessRule), typeof(AccessRule<T>) );
		}
        public override System.Security.AccessControl.AuditRule AuditRuleFactory( System.Security.Principal.IdentityReference identityReference, int accessMask, bool isInherited, System.Security.AccessControl.InheritanceFlags inheritanceFlags, System.Security.AccessControl.PropagationFlags propagationFlags, System.Security.AccessControl.AuditFlags flags ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AuditRuleFactory), typeof(IdentityReference), typeof(Int32), typeof(Boolean), typeof(InheritanceFlags), typeof(PropagationFlags), typeof(AuditFlags) );
            return default( System.Security.AccessControl.AuditRule );

		}
        public virtual void AddAuditRule( AuditRule<T> rule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddAuditRule), typeof(AuditRule<T>) );
		}
        public virtual bool RemoveAuditRule( AuditRule<T> rule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RemoveAuditRule), typeof(AuditRule<T>) );
            return default( bool );

		}
        public virtual void RemoveAuditRuleAll( AuditRule<T> rule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RemoveAuditRuleAll), typeof(AuditRule<T>) );
		}
        public virtual void RemoveAuditRuleSpecific( AuditRule<T> rule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RemoveAuditRuleSpecific), typeof(AuditRule<T>) );
		}
        public virtual void SetAuditRule( AuditRule<T> rule ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetAuditRule), typeof(AuditRule<T>) );
		}
        protected void Persist( System.Runtime.InteropServices.SafeHandle handle ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Persist), typeof(SafeHandle) );
		}
        protected void Persist( string name ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Persist), typeof(String) );
		}
    }
}