// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System;

namespace System.Security.AccessControl {
    public class PrivilegeNotHeldException: System.UnauthorizedAccessException {

        public string PrivilegeName {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PrivilegeName));
				return default (String);
			}
		}
        public PrivilegeNotHeldException(  ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PrivilegeNotHeldException));
            }
        public PrivilegeNotHeldException( string privilege ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PrivilegeNotHeldException), typeof(String));
            }
        public PrivilegeNotHeldException( string privilege, System.Exception inner ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PrivilegeNotHeldException), typeof(String), typeof(Exception));
            }
        public void GetObjectData( System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetObjectData), typeof(SerializationInfo), typeof(StreamingContext) );
		}
    }
}