// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Security.AccessControl;
using System.Security;
using System.Security.Principal;

namespace System.Security.AccessControl {
    public class SemaphoreAuditRule: System.Security.AccessControl.AuditRule {

        public System.Security.AccessControl.SemaphoreRights SemaphoreRights {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SemaphoreRights));
				return default (SemaphoreRights);
			}
		}
        public SemaphoreAuditRule( System.Security.Principal.IdentityReference identity, System.Security.AccessControl.SemaphoreRights eventRights, System.Security.AccessControl.AuditFlags flags )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SemaphoreAuditRule), typeof(IdentityReference), typeof(SemaphoreRights), typeof(AuditFlags));
            }
    }
}