// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.Remoting.Activation;
using System;
using System.Runtime.Remoting.Proxies;

namespace System.Runtime.Remoting.Services {
    public class EnterpriseServicesHelper {

        public static System.Runtime.Remoting.Activation.IConstructionReturnMessage CreateConstructionReturnMessage( System.Runtime.Remoting.Activation.IConstructionCallMessage ctorMsg, System.MarshalByRefObject retObj ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CreateConstructionReturnMessage), typeof(IConstructionCallMessage), typeof(MarshalByRefObject) );
            return default( System.Runtime.Remoting.Activation.IConstructionReturnMessage );

		}
        public static void SwitchWrappers( System.Runtime.Remoting.Proxies.RealProxy oldcp, System.Runtime.Remoting.Proxies.RealProxy newcp ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SwitchWrappers), typeof(RealProxy), typeof(RealProxy) );
		}
        public static System.Object WrapIUnknownWithComObject( System.IntPtr punk ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(WrapIUnknownWithComObject), typeof(IntPtr) );
            return default( System.Object );

		}
    }
}