// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.IO.Pipes;
using System.IO;

namespace System.IO.Pipes {
    public class AnonymousPipeClientStream: System.IO.Pipes.PipeStream {

        public new System.IO.Pipes.PipeTransmissionMode ReadMode {
			set {
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadMode));
			 }
		}
        public override System.IO.Pipes.PipeTransmissionMode TransmissionMode {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(TransmissionMode));
				return default (PipeTransmissionMode);
			}
		}
        public AnonymousPipeClientStream( string pipeHandleAsString )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AnonymousPipeClientStream), typeof(String));
            }
        public AnonymousPipeClientStream( System.IO.Pipes.PipeDirection direction, string pipeHandleAsString )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AnonymousPipeClientStream), typeof(PipeDirection), typeof(String));
            }

    }
}