// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.IO.Pipes;

namespace System.IO.Pipes {
    public enum PipeOptions {
        None = 0,
        WriteThrough = -2147483648,
        Asynchronous = 1073741824
    }
}