// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Collections.Concurrent;

namespace System.Collections.Concurrent {
    public enum EnumerablePartitionerOptions {
        None = 0,
        NoBuffering = 1
    }
}