// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Globalization;

namespace System.Globalization {
    public class JapaneseLunisolarCalendar: System.Globalization.EastAsianLunisolarCalendar {

        internal const int JapaneseEra = 1;

        internal const int MIN_LUNISOLAR_YEAR = 1960;

        internal const int MAX_LUNISOLAR_YEAR = 2049;

        internal const int MIN_GREGORIAN_YEAR = 1960;

        internal const int MIN_GREGORIAN_MONTH = 1;

        internal const int MIN_GREGORIAN_DAY = 28;

        internal const int MAX_GREGORIAN_YEAR = 2050;

        internal const int MAX_GREGORIAN_MONTH = 1;

        internal const int MAX_GREGORIAN_DAY = 22;

        public override System.DateTime MinSupportedDateTime {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MinSupportedDateTime));
				return default (DateTime);
			}
		}
        public override System.DateTime MaxSupportedDateTime {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MaxSupportedDateTime));
				return default (DateTime);
			}
		}
        internal override int MinCalendarYear {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MinCalendarYear));
				return default (Int32);
			}
		}
        internal override int MaxCalendarYear {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MaxCalendarYear));
				return default (Int32);
			}
		}
        internal override System.DateTime MinDate {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MinDate));
				return default (DateTime);
			}
		}
        internal override System.DateTime MaxDate {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MaxDate));
				return default (DateTime);
			}
		}
        internal override CalendarId BaseCalendarID {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(BaseCalendarID));
				return default (Int32);
			}
		}
        internal override CalendarId ID {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ID));
				return default (Int32);
			}
		}
        public override int[] Eras {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Eras));
				return default (Int32[]);
			}
		}
        internal override int GetYearInfo( int LunarYear, int Index ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetYearInfo), typeof(Int32), typeof(Int32) );
            return default( int );

		}
        internal override int GetYear( int year, System.DateTime time ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetYear), typeof(Int32), typeof(DateTime) );
            return default( int );

		}
        internal override int GetGregorianYear( int year, int era ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetGregorianYear), typeof(Int32), typeof(Int32) );
            return default( int );

		}
        public override int GetEra( System.DateTime time ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetEra), typeof(DateTime) );
            return default( int );

		}
    }
}