// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Globalization;

namespace System.Globalization {
    public class SortKey {

        public virtual string OriginalString {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OriginalString));
				return default (String);
			}
		}
        public virtual byte[][] KeyData {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(KeyData));
				return default(byte[][]);
			}
		}
        public static int Compare( System.Globalization.SortKey sortkey1, System.Globalization.SortKey sortkey2 ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Compare), typeof(SortKey), typeof(SortKey) );
            return default( int );

		}
        public override bool Equals( System.Object value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );

		}
    }
}