// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System;

namespace System.Runtime.Remoting.Metadata.W3cXsd2001 {
    public class SoapDay: System.Runtime.Remoting.Metadata.W3cXsd2001.ISoapXsd {

        public System.DateTime Value { get; set; }
        public static string XsdType { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(XsdType));
				return default (String);
			}
		}
        public SoapDay(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SoapDay));
            }
        public SoapDay( System.DateTime value )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SoapDay), typeof(DateTime));
            }
        public string GetXsdType() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetXsdType) );
            return default( string );
        
		}
        public static System.Runtime.Remoting.Metadata.W3cXsd2001.SoapDay Parse( string value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Parse), typeof(String) );
            return default( System.Runtime.Remoting.Metadata.W3cXsd2001.SoapDay );
        
		}
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );
        
		}
    }
}