// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System;

namespace System.Runtime.Remoting.Metadata.W3cXsd2001 {
    public class SoapNormalizedString: System.Runtime.Remoting.Metadata.W3cXsd2001.ISoapXsd {

        public string Value { get; set; }
        public static string XsdType { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(XsdType));
				return default (String);
			}
		}
        public SoapNormalizedString(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SoapNormalizedString));
            }
        public SoapNormalizedString( string value )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SoapNormalizedString), typeof(String));
            }
        public string GetXsdType() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetXsdType) );
            return default( string );
        
		}
        public static System.Runtime.Remoting.Metadata.W3cXsd2001.SoapNormalizedString Parse( string value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Parse), typeof(String) );
            return default( System.Runtime.Remoting.Metadata.W3cXsd2001.SoapNormalizedString );
        
		}
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );
        
		}
    }
}