// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.Runtime.Remoting.Metadata.W3cXsd2001 {
    public class SoapDuration {

        public static string XsdType { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(XsdType));
				return default (String);
			}
		}
        public static System.TimeSpan Parse( string value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Parse), typeof(String) );
            return default( System.TimeSpan );
        
		}
        public static string ToString( System.TimeSpan timeSpan ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString), typeof(TimeSpan) );
            return default( string );
        
		}
    }
}