// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System;

namespace System.Runtime.Remoting.Metadata.W3cXsd2001 {
    public class SoapBase64Binary: System.Runtime.Remoting.Metadata.W3cXsd2001.ISoapXsd {

        public byte[][] Value { get; set; }
        public static string XsdType { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(XsdType));
				return default (String);
			}
		}
        public SoapBase64Binary(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SoapBase64Binary));
            }
        public SoapBase64Binary( byte[] value )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SoapBase64Binary), typeof(Byte[]));
            }
        public string GetXsdType() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetXsdType) );
            return default( string );
        
		}
        public static System.Runtime.Remoting.Metadata.W3cXsd2001.SoapBase64Binary Parse( string value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Parse), typeof(String) );
            return default( System.Runtime.Remoting.Metadata.W3cXsd2001.SoapBase64Binary );
        
		}
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );
        
		}
    }
}