// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System;

namespace System.Runtime.Remoting.Metadata.W3cXsd2001 {
    public class SoapInteger: System.Runtime.Remoting.Metadata.W3cXsd2001.ISoapXsd {

        public System.Decimal Value { get; set; }
        public static string XsdType { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(XsdType));
				return default (String);
			}
		}
        public SoapInteger(  )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SoapInteger));
            }
        public SoapInteger( System.Decimal value )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SoapInteger), typeof(Decimal));
            }
        public string GetXsdType() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetXsdType) );
            return default( string );
        
		}
        public static System.Runtime.Remoting.Metadata.W3cXsd2001.SoapInteger Parse( string value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Parse), typeof(String) );
            return default( System.Runtime.Remoting.Metadata.W3cXsd2001.SoapInteger );
        
		}
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );
        
		}
    }
}