// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.ComponentModel;
using System;
using System.Threading;
using System.Runtime.Serialization;

namespace System.ComponentModel {
    public class BackgroundWorker: System.ComponentModel.Component {

        public bool CancellationPending { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CancellationPending));
				return default (Boolean);
			}
		}
        public bool IsBusy { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsBusy));
				return default (Boolean);
			}
		}
        public bool WorkerReportsProgress { get; set; }
        public bool WorkerSupportsCancellation { get; set; }
        #pragma warning disable 67
        public event System.ComponentModel.DoWorkEventHandler DoWork;
        public event System.ComponentModel.ProgressChangedEventHandler ProgressChanged;
        public event System.ComponentModel.RunWorkerCompletedEventHandler RunWorkerCompleted;
        #pragma warning disable 67

        public void CancelAsync() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CancelAsync) ); 
		}
        protected virtual void OnDoWork( System.ComponentModel.DoWorkEventArgs e ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OnDoWork), typeof(DoWorkEventArgs) ); 
		}
        protected virtual void OnRunWorkerCompleted( System.ComponentModel.RunWorkerCompletedEventArgs e ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OnRunWorkerCompleted), typeof(RunWorkerCompletedEventArgs) ); 
		}
        protected virtual void OnProgressChanged( System.ComponentModel.ProgressChangedEventArgs e ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OnProgressChanged), typeof(ProgressChangedEventArgs) ); 
		}
        public void ReportProgress( int percentProgress ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReportProgress), typeof(Int32) ); 
		}
        public void ReportProgress( int percentProgress, System.Object userState ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReportProgress), typeof(Int32), typeof(Object) ); 
		}
        public void RunWorkerAsync() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RunWorkerAsync) ); 
		}
        public void RunWorkerAsync( System.Object argument ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RunWorkerAsync), typeof(Object) ); 
		}
    }
}