// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.ComponentModel;
using System;

namespace System.ComponentModel {
    public class BindableAttribute: System.Attribute {

        public bool Bindable {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Bindable));
				return default (Boolean);
			}
		}
        public System.ComponentModel.BindingDirection Direction {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Direction));
				return default (BindingDirection);
			}
		}
        public BindableAttribute( bool bindable )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(BindableAttribute), typeof(Boolean));
            }
        public BindableAttribute( bool bindable, System.ComponentModel.BindingDirection direction )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(BindableAttribute), typeof(Boolean), typeof(BindingDirection));
            }
        public BindableAttribute( System.ComponentModel.BindableSupport flags )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(BindableAttribute), typeof(BindableSupport));
            }
        public BindableAttribute( System.ComponentModel.BindableSupport flags, System.ComponentModel.BindingDirection direction )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(BindableAttribute), typeof(BindableSupport), typeof(BindingDirection));
            }
        public override bool Equals( System.Object obj ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
        public bool IsDefaultAttribute() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsDefaultAttribute) );
            return default( bool );

		}
    }
}