// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;
using System.ComponentModel;

namespace System.ComponentModel {
    public class DataObjectMethodAttribute: System.Attribute {

        public bool IsDefault {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsDefault));
				return default (Boolean);
			}
		}
        public System.ComponentModel.DataObjectMethodType MethodType {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(MethodType));
				return default (DataObjectMethodType);
			}
		}
        public DataObjectMethodAttribute( System.ComponentModel.DataObjectMethodType methodType )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DataObjectMethodAttribute), typeof(DataObjectMethodType));
            }
        public DataObjectMethodAttribute( System.ComponentModel.DataObjectMethodType methodType, bool isDefault )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DataObjectMethodAttribute), typeof(DataObjectMethodType), typeof(Boolean));
            }
        public override bool Equals( System.Object obj ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
        public bool Match( System.Object obj ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Match), typeof(Object) );
            return default( bool );

		}
    }
}