// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel;
using System.Globalization;

namespace System.ComponentModel {
    public class DecimalConverter: System.ComponentModel.BaseNumberConverter {

        internal override bool AllowHex { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AllowHex));
				return default (Boolean);
			}
		}
        internal override System.Type TargetType { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(TargetType));
				return default (Type);
			}
		}
        public override bool CanConvertTo( System.ComponentModel.ITypeDescriptorContext context, System.Type destinationType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CanConvertTo), typeof(ITypeDescriptorContext), typeof(Type) );
            return default( bool );
        
		}
        public override System.Object ConvertTo( System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, System.Object value, System.Type destinationType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ConvertTo), typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(Object), typeof(Type) );
            return default( System.Object );
        
		}
        internal override System.Object FromString( string value, int radix ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FromString), typeof(String), typeof(Int32) );
            return default( System.Object );
        
		}
        internal override System.Object FromString( string value, System.Globalization.NumberFormatInfo formatInfo ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FromString), typeof(String), typeof(NumberFormatInfo) );
            return default( System.Object );
        
		}
        internal override System.Object FromString( string value, System.Globalization.CultureInfo culture ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FromString), typeof(String), typeof(CultureInfo) );
            return default( System.Object );
        
		}
        internal override string ToString( System.Object value, System.Globalization.NumberFormatInfo formatInfo ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString), typeof(Object), typeof(NumberFormatInfo) );
            return default( string );
        
		}
    }
}