// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;
using System.ComponentModel;

namespace System.ComponentModel {
    public class DesignOnlyAttribute: System.Attribute {

        public bool IsDesignOnly {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsDesignOnly));
				return default (Boolean);
			}
		}
        public DesignOnlyAttribute( bool isDesignOnly )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DesignOnlyAttribute), typeof(Boolean));
            }
        public bool IsDefaultAttribute() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsDefaultAttribute) );
            return default( bool );

		}
        public override bool Equals( System.Object obj ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
    }
}