// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;
using System.ComponentModel;

namespace System.ComponentModel {
    public class DesignerCategoryAttribute: System.Attribute {
        public string Category {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Category));
				return default (String);
			}
		}
        public System.Object TypeId {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(TypeId));
				return default (Object);
			}
		}
        public DesignerCategoryAttribute(  )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DesignerCategoryAttribute));
            }
        public DesignerCategoryAttribute( string category )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DesignerCategoryAttribute), typeof(String));
            }
        public override bool Equals( System.Object obj ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
        public bool IsDefaultAttribute() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsDefaultAttribute) );
            return default( bool );

		}
    }
}