// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel;

namespace System.ComponentModel {
    public class EventHandlerList: System.IDisposable {

        public System.Delegate this[System.Object key] {
			get {
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod("indexer");
			return default( System.Delegate ); 
		}
			set {
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod("indexer");
		} }
        public void AddHandler( System.Object key, System.Delegate value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddHandler), typeof(Object), typeof(Delegate) ); 
		}
        public void AddHandlers( System.ComponentModel.EventHandlerList listToAddFrom ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(AddHandlers), typeof(EventHandlerList) ); 
		}
        public void Dispose() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Dispose) ); 
		}
        public void RemoveHandler( System.Object key, System.Delegate value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(RemoveHandler), typeof(Object), typeof(Delegate) ); 
		}
    }
}