// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.ComponentModel;
using System;

namespace System.ComponentModel {
    public interface IComNativeDescriptorHandler {

        System.ComponentModel.AttributeCollection GetAttributes( System.Object component );

        string GetClassName( System.Object component );

        System.ComponentModel.TypeConverter GetConverter( System.Object component );

        System.ComponentModel.EventDescriptor GetDefaultEvent( System.Object component );

        System.ComponentModel.PropertyDescriptor GetDefaultProperty( System.Object component );

        System.Object GetEditor( System.Object component, System.Type baseEditorType );

        string GetName( System.Object component );

        System.ComponentModel.EventDescriptorCollection GetEvents( System.Object component );

        System.ComponentModel.EventDescriptorCollection GetEvents( System.Object component, System.Attribute[] attributes );

        System.ComponentModel.PropertyDescriptorCollection GetProperties( System.Object component, System.Attribute[] attributes );

        System.Object GetPropertyValue( System.Object component, string propertyName, ref System.Boolean success );

        System.Object GetPropertyValue( System.Object component, int dispid, ref System.Boolean success );

    }
}