// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.ComponentModel;
using System;

namespace System.ComponentModel {
    public interface ICustomTypeDescriptor {

        System.ComponentModel.AttributeCollection GetAttributes();

        string GetClassName();

        string GetComponentName();

        System.ComponentModel.TypeConverter GetConverter();

        System.ComponentModel.EventDescriptor GetDefaultEvent();

        System.ComponentModel.PropertyDescriptor GetDefaultProperty();

        System.Object GetEditor( System.Type editorBaseType );

        System.ComponentModel.EventDescriptorCollection GetEvents();

        System.ComponentModel.EventDescriptorCollection GetEvents( System.Attribute[] attributes );

        System.ComponentModel.PropertyDescriptorCollection GetProperties();

        System.ComponentModel.PropertyDescriptorCollection GetProperties( System.Attribute[] attributes );

        System.Object GetPropertyOwner( System.ComponentModel.PropertyDescriptor pd );

    }
}