// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel;

namespace System.ComponentModel {
    public interface INestedSite: System.ComponentModel.ISite {

        string FullName { get; }
    }
}