// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;

namespace System.ComponentModel {
    public class InvalidEnumArgumentException: System.ArgumentException {

        public InvalidEnumArgumentException(  ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InvalidEnumArgumentException));
            }
        public InvalidEnumArgumentException( string message ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InvalidEnumArgumentException), typeof(String));
            }
        public InvalidEnumArgumentException( string message, System.Exception innerException ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InvalidEnumArgumentException), typeof(String), typeof(Exception));
            }
        public InvalidEnumArgumentException( string argumentName, int invalidValue, System.Type enumClass ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InvalidEnumArgumentException), typeof(String), typeof(Int32), typeof(Type));
            }
    }
}