// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;

namespace System.ComponentModel {
    public interface ISynchronizeInvoke {

        bool InvokeRequired { get; }
        System.IAsyncResult BeginInvoke( System.Delegate method, System.Object[] args );

        System.Object EndInvoke( System.IAsyncResult result );

        System.Object Invoke( System.Delegate method, System.Object[] args );

    }
}