// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel;

namespace System.ComponentModel {
    public interface ITypedList {

        string GetListName( System.ComponentModel.PropertyDescriptor[] listAccessors );

        System.ComponentModel.PropertyDescriptorCollection GetItemProperties( System.ComponentModel.PropertyDescriptor[] listAccessors );

    }
}