// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel;
using System.Reflection;

namespace System.ComponentModel {
    public class LicenseContext {

        public virtual System.ComponentModel.LicenseUsageMode UsageMode {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(UsageMode));
				return default (LicenseUsageMode);
			}
		}
        public virtual string GetSavedLicenseKey( System.Type type, System.Reflection.Assembly resourceAssembly ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetSavedLicenseKey), typeof(Type), typeof(Assembly) );
            return default( string );

		}
        public virtual System.Object GetService( System.Type type ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetService), typeof(Type) );
            return default( System.Object );

		}
        public virtual void SetSavedLicenseKey( System.Type type, string key ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(SetSavedLicenseKey), typeof(Type), typeof(String) );
		}
    }
}