// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.ComponentModel;
using System;

namespace System.ComponentModel {
    public class ListChangedEventArgs: System.EventArgs {

        public System.ComponentModel.ListChangedType ListChangedType { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ListChangedType));
				return default (ListChangedType);
			}
		}
        public int NewIndex { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(NewIndex));
				return default (Int32);
			}
		}
        public int OldIndex { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(OldIndex));
				return default (Int32);
			}
		}
        public System.ComponentModel.PropertyDescriptor PropertyDescriptor { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(PropertyDescriptor));
				return default (PropertyDescriptor);
			}
		}
        public ListChangedEventArgs( System.ComponentModel.ListChangedType listChangedType, int newIndex )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ListChangedEventArgs), typeof(ListChangedType), typeof(Int32));
            }
        public ListChangedEventArgs( System.ComponentModel.ListChangedType listChangedType, int newIndex, System.ComponentModel.PropertyDescriptor propDesc )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ListChangedEventArgs), typeof(ListChangedType), typeof(Int32), typeof(PropertyDescriptor));
            }
        public ListChangedEventArgs( System.ComponentModel.ListChangedType listChangedType, System.ComponentModel.PropertyDescriptor propDesc )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ListChangedEventArgs), typeof(ListChangedType), typeof(PropertyDescriptor));
            }
        public ListChangedEventArgs( System.ComponentModel.ListChangedType listChangedType, int newIndex, int oldIndex )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ListChangedEventArgs), typeof(ListChangedType), typeof(Int32), typeof(Int32));
            }
    }
}