// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.ComponentModel;
using System;

namespace System.ComponentModel {
    public class ListSortDescription {

        public System.ComponentModel.PropertyDescriptor PropertyDescriptor { get; set; }
        public System.ComponentModel.ListSortDirection SortDirection { get; set; }
        public ListSortDescription( System.ComponentModel.PropertyDescriptor property, System.ComponentModel.ListSortDirection direction )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ListSortDescription), typeof(PropertyDescriptor), typeof(ListSortDirection));
            }
    }
}