// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel;

namespace System.ComponentModel {
    public class MarshalByValueComponent: System.ComponentModel.IComponent {

        internal System.ComponentModel.EventHandlerList Events {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Events));
				return default (EventHandlerList);
			}
		}
        public virtual System.ComponentModel.ISite Site { get; set; }
        public virtual System.ComponentModel.IContainer Container {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Container));
				return default (IContainer);
			}
		}
        public virtual bool DesignMode {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(DesignMode));
				return default (Boolean);
			}
		}
        #pragma warning disable 67
        public event System.EventHandler Disposed;
        #pragma warning disable 67

        public void Dispose() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Dispose) );
		}
        protected virtual void Dispose( bool disposing ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Dispose), typeof(Boolean) );
		}
        public virtual System.Object GetService( System.Type service ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetService), typeof(Type) );
            return default( System.Object );

		}
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );

		}
    }
}