// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.ComponentModel;
using System;

namespace System.ComponentModel {
    public class NotifyParentPropertyAttribute: System.Attribute {

        public bool NotifyParent {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(NotifyParent));
				return default (Boolean);
			}
		}
        public NotifyParentPropertyAttribute( bool notifyParent )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(NotifyParentPropertyAttribute), typeof(Boolean));
            }
        public override bool Equals( System.Object obj ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
        public bool IsDefaultAttribute() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsDefaultAttribute) );
            return default( bool );

		}
    }
}