// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel;

namespace System.ComponentModel {
    public enum PropertyTabScope {
        Static = 0,
        Global = 1,
        Document = 2,
        Component = 3
    }
}