// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System;
using System.ComponentModel;

namespace System.ComponentModel {
    public class ReadOnlyAttribute: System.Attribute {


        public bool IsReadOnly {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsReadOnly));
				return default (Boolean);
			}
		}
        public ReadOnlyAttribute( bool isReadOnly )  {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReadOnlyAttribute), typeof(Boolean));
            }
        public override bool Equals( System.Object value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Equals), typeof(Object) );
            return default( bool );

		}
        public override int GetHashCode() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetHashCode) );
            return default( int );

		}
        public bool IsDefaultAttribute() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsDefaultAttribute) );
            return default( bool );

		}
    }
}