// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.ComponentModel;
using System.Globalization;
using System.Collections;

namespace System.ComponentModel {
    public class ReferenceConverter: System.ComponentModel.TypeConverter {

        public ReferenceConverter( System.Type type )  { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ReferenceConverter), typeof(Type));
            }
        public override bool CanConvertFrom( System.ComponentModel.ITypeDescriptorContext context, System.Type sourceType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(CanConvertFrom), typeof(ITypeDescriptorContext), typeof(Type) );
            return default( bool );
        
		}
        public override System.Object ConvertFrom( System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, System.Object value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ConvertFrom), typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(Object) );
            return default( System.Object );
        
		}
        public override System.Object ConvertTo( System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, System.Object value, System.Type destinationType ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ConvertTo), typeof(ITypeDescriptorContext), typeof(CultureInfo), typeof(Object), typeof(Type) );
            return default( System.Object );
        
		}
        public override System.ComponentModel.TypeConverter.StandardValuesCollection GetStandardValues( System.ComponentModel.ITypeDescriptorContext context ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetStandardValues), typeof(ITypeDescriptorContext) );
            return default( System.ComponentModel.TypeConverter.StandardValuesCollection );
        
		}
        public override bool GetStandardValuesExclusive( System.ComponentModel.ITypeDescriptorContext context ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetStandardValuesExclusive), typeof(ITypeDescriptorContext) );
            return default( bool );
        
		}
        public override bool GetStandardValuesSupported( System.ComponentModel.ITypeDescriptorContext context ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetStandardValuesSupported), typeof(ITypeDescriptorContext) );
            return default( bool );
        
		}
        protected virtual bool IsValueAllowed( System.ComponentModel.ITypeDescriptorContext context, System.Object value ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(IsValueAllowed), typeof(ITypeDescriptorContext), typeof(Object) );
            return default( bool );
        
		}
    }
}