// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security;

namespace System.Security {
    public enum HostSecurityManagerOptions {
        None = 0,
        HostAppDomainEvidence = 1,
        HostPolicyLevel = 2,
        HostAssemblyEvidence = 4,
        HostDetermineApplicationTrust = 8,
        HostResolvePolicy = 16,
        AllFlags = 31
    }
}