// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System;
using System.Security;

namespace System.Security {
    public enum SecurityContextSource {
        CurrentAppDomain = 0,
        CurrentAssembly = 1
    }
}