// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.Remoting.Messaging;
using System.Runtime.Remoting.Activation;
using System.Runtime.Serialization;
using System.Collections;
using System;

namespace System.Runtime.Remoting.Messaging {
    public class ConstructionResponse: System.Runtime.Remoting.Messaging.MethodResponse, System.Runtime.Remoting.Activation.IConstructionReturnMessage {

        public override System.Collections.IDictionary Properties { 
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Properties));
				return default (IDictionary);
			}
		}
        public ConstructionResponse( System.Runtime.Remoting.Messaging.Header[] h, System.Runtime.Remoting.Messaging.IMethodCallMessage mcm ) : base( default( System.Runtime.Remoting.Messaging.Header[] ), default( System.Runtime.Remoting.Messaging.IMethodCallMessage ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ConstructionResponse), typeof(Header[]), typeof(IMethodCallMessage));
            }
    }
}