// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System;

namespace System.IO {
    public class FileNotFoundException: System.IO.IOException {

        public override string Message {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(Message));
				return default (String);
			}
		}
        public string FileName {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FileName));
				return default (String);
			}
		}
        public string FusionLog {
			get{
				Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FusionLog));
				return default (String);
			}
		}
        public FileNotFoundException(  ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FileNotFoundException));
            }
        public FileNotFoundException( string message ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FileNotFoundException), typeof(String));
            }
        public FileNotFoundException( string message, System.Exception innerException ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FileNotFoundException), typeof(String), typeof(Exception));
            }
        public FileNotFoundException( string message, string fileName ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FileNotFoundException), typeof(String), typeof(String));
            }
        public FileNotFoundException( string message, string fileName, System.Exception innerException ) : base( default( string ) ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(FileNotFoundException), typeof(String), typeof(String), typeof(Exception));
            }
        public override string ToString() {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(ToString) );
            return default( string );

		}
        public void GetObjectData( System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context ) {
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(GetObjectData), typeof(SerializationInfo), typeof(StreamingContext) );
		}
    }
}