// THIS FILE WAS AUTOMATICALLY GENERATED BY STUBBER

using System.Runtime.InteropServices;
using System.Runtime.Serialization;
using System;

namespace System.IO {
    public class InvalidDataException: System.SystemException {

        public InvalidDataException(  ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InvalidDataException));
            }
        public InvalidDataException( string message ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InvalidDataException), typeof(String));
            }
        public InvalidDataException( string message, System.Exception innerException ) : base( default( string ) ) { 
			Bridge.Luna.Utils.Debug.WarnNotImplementedMethod(nameof(InvalidDataException), typeof(String), typeof(Exception));
            }
    }
}