name: Bridge Tests

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install packages
        working-directory: /LunaToolbox
        run: npm install

      - name: Run eslint
        working-directory: /LunaToolbox
        run: npm run eslint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker
        run: docker build -t tests .

      - name: Run Docker tests
        run: docker run -t tests ltb test --ci -nd
